import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'te' | 'ta' | 'kn' | 'pa';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
  flag: string;
}

export const languages: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ', flag: '🇮🇳' }
];

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    portal_title: 'SmartProcure',
    govt_title: 'Ministry of Consumer Affairs, Food & Public Distribution',
    govt_badge: 'Govt. Portal',
    toll_free: 'Toll-Free Kisan Helpline',
    nav_dashboard: 'Dashboard',
    nav_book_slot: 'Book Slot',
    nav_weather: 'Weather Forecast',
    nav_guidelines: 'Required Checklist',
    nav_my_queue: 'My Queue',
    nav_procurement: 'Procurement',
    nav_payments: 'Payments (DBT)',
    nav_notifications: 'Notifications',
    nav_profile: 'My Profile',
    nav_login: 'Sign In',
    nav_register: 'Register',
    nav_logout: 'Logout',

    tagline_main: '"Smart Queues. Faster Procurement. Better Farming."',
    tagline_desc: 'An intelligent procurement management platform that reduces waiting time, prevents overcrowding, and gives farmers real-time visibility into weather, procurement, and payments.',
    hero_badge: '27+ Crops • 16 Regional Hubs • 6 Languages',
    btn_farmer_login: 'Farmer Login',
    btn_officer_login: 'Centre Officer Login',
    btn_admin_login: 'Admin Dashboard',

    stat_crops: '27+ Crops',
    stat_crops_sub: 'Grains, Pulses, Oilseeds & Cotton',
    stat_centres: '16 Centres',
    stat_centres_sub: 'Multi-State Connected Hubs',
    stat_wait_time: '32 min',
    stat_wait_time_sub: 'Avg Waiting Time (Down 65%)',
    stat_dbt: '100%',
    stat_dbt_sub: 'Direct Benefit Transfer (DBT)',

    key_features_heading: 'Key Platform Features',
    key_features_subheading: 'Designed to bring digital convenience, multi-crop support, weather forecasting, location proximity, and multi-language accessibility to grain procurement yards across India.',
    feat_multicrop_title: 'Multi-Crop Slot Allocation',
    feat_multicrop_desc: 'Book slots for 25+ major Indian crops (Cereals, Pulses, Oilseeds, Cotton, Spices) simultaneously in one ticket.',
    feat_location_title: 'Auto-Location & Nearest Hubs',
    feat_location_desc: 'GPS proximity engine automatically computes road distances to nearest procurement centres across districts.',
    feat_language_title: 'Multi-Language Accessibility',
    feat_language_desc: 'Full regional language support in English, Telugu (తెలుగు), Hindi (हिन्दी), Tamil (தமிழ்), Kannada (ಕನ್ನಡ), and Punjabi (ਪੰਜਾਬੀ).',
    feat_queue_title: 'Live Queue & Wait Estimates',
    feat_queue_desc: 'Know your token position and AI estimated waiting time in real time before arriving at the yard.',
    feat_pipeline_title: 'Procurement Pipeline Tracking',
    feat_pipeline_desc: 'Track your produce through an 8-stage visual timeline from arrival to automated moisture & quality grading.',
    feat_dbt_title: 'Direct DBT Payment Transparency',
    feat_dbt_desc: 'Know exactly when your procurement payment is credited directly to your bank account via Direct Benefit Transfer.',

    how_it_works: 'How SmartProcure Works',
    how_desc: 'Seamless 6-step workflow for hassle-free crop procurement',
    step1_title: 'Register / Sign In',
    step1_desc: 'Login with mobile OTP or registered Farmer ID',
    step2_title: 'Select Crops',
    step2_desc: 'Choose single or multiple crops with quantities',
    step3_title: 'Nearest Centre',
    step3_desc: 'GPS automatically ranks nearest yards by queue',
    step4_title: 'Get Token & QR',
    step4_desc: 'Receive instant digital appointment QR pass',
    step5_title: 'Live Queue Tracking',
    step5_desc: 'Arrive on time when your token is called',
    step6_title: 'Instant DBT Credit',
    step6_desc: 'Receive MSP payment voucher and bank credit',

    ready_cta: 'Ready to Experience Zero-Wait Procurement?',
    ready_desc: 'Book a multi-crop delivery slot, verify weather forecasts, and check procurement centre guidelines for a smooth visit.',
    btn_launch_booking: 'Launch Multi-Crop Booking',

    detect_location: 'Detect My Location (GPS)',
    location_detected: 'Location Detected',
    select_location: 'Select Your Location / District',
    enter_village: 'Village / Mandal Name',
    enter_address: 'Delivery / Farm Address',
    district_label: 'District',
    state_label: 'State',
    gps_accuracy: 'GPS Proximity Calculated',
    near_you: 'Nearest Centres to You',

    reg_portal_title: 'Farmer Registration Portal',
    reg_create_account: 'Create Farmer Account',
    reg_step1_label: 'Personal & Location',
    reg_step2_label: 'Produce Info',
    reg_step3_label: 'Procurement Centre',
    reg_step1_title: 'Step 1: Farmer Identity & Location',
    reg_step2_title: 'Step 2: Primary Crop & Produce Info',
    reg_step3_title: 'Step 3: Preferred Procurement Centre',
    full_name_label: 'Full Name *',
    name_placeholder: 'e.g. Ravi Kumar',
    mobile_placeholder: 'e.g. 9876543210',
    village_placeholder: 'e.g. Pedakakani',
    address_placeholder: 'Door number, street name, pincode',
    crop_type_label: 'Crop Type (27+ Choices) *',
    variety_label: 'Variety / Grade *',
    variety_placeholder: 'e.g. Sona Masoori Grade A',
    expected_qty_label: 'Expected Quantity (in Quintals) *',
    qty_helper: '1 Quintal = 100 kg. Government MSP applicable.',
    centres_matching: 'Available centres matching',
    capacity_per_day: 'Capacity / Day',
    btn_prev_step: 'Previous Step',
    btn_next_step: 'Next Step',
    btn_complete_reg: 'Complete Registration & Book Slot',
    already_registered: 'Already registered? Sign In',

    signin_title: 'SmartProcure Unified Sign In',
    signin_desc: 'Secure Sign In & Authentication for Farmers, Procurement Officers, and Government Authorities.',
    tab_farmer: 'Farmer',
    tab_officer: 'Officer',
    tab_admin: 'Admin',
    farmer_otp_title: 'Farmer Mobile OTP & Location Sign In',
    farmer_otp_desc: 'Enter your mobile number, verify your farm district/location, and receive an instant verification OTP.',
    mobile_label: 'Registered Mobile Number / Farmer ID',
    change_mobile: 'Change Mobile',
    enter_otp: 'Enter 4-Digit OTP Code',
    otp_hint: 'Hint: Enter the 4-digit code sent to your mobile',
    resend_otp: 'Resend OTP Code',
    resend_in: 'Resend in',
    btn_get_otp: 'Get OTP Verification Code',
    btn_verify_login: 'Verify & Sign In to Dashboard',
    new_farmer_register: 'New Farmer? Register Account',
    officer_title: 'Centre Officer Terminal Access',
    officer_desc: 'Authorized procurement yard officers and counter managers login portal.',
    station_code: 'Station / Yard Code',
    department_password: 'Departmental Password',
    btn_officer_login_action: 'Login to Officer Terminal',
    admin_title: 'District / State Admin Login',
    admin_desc: 'Government administration portal for capacity management & analytics.',
    admin_id: 'Government Email / Admin ID',
    security_pin: 'Security Passcode / Token PIN',
    btn_admin_login_action: 'Authenticate & Access Admin Suite',
    ssl_encrypted: '256-bit SSL Encrypted',
    aadhaar_integrated: 'Aadhaar Integrated',
    return_home: '← Return to Home Page',

    slot_booking_title: 'Book Procurement Appointment Slot',
    select_crops: 'Select Crop(s)',
    multi_crop_badge: 'Multi-Crop Support',
    add_crop: 'Add Another Crop',
    remove_crop: 'Remove',
    total_quantity: 'Total Quantity',
    total_est_payout: 'Total Est. MSP Payout',
    step_crop: '1. Crops',
    step_quantity: '2. Quantities',
    step_centre: '3. Centre',
    step_date: '4. Date',
    step_slot: '5. Time Slot',
    step_summary: '6. Summary',
    search_crop_placeholder: 'Search crop (e.g. Paddy, Cotton, Mustard)...',
    search_centre_placeholder: 'Search centre or district...',
    all_categories: 'All Categories',
    cereals: 'Cereals & Grains',
    pulses: 'Pulses & Dals',
    oilseeds: 'Oilseeds',
    commercial: 'Commercial & Cash Crops',
    spices: 'Spices',
    est_wait: 'Est. Wait',
    live_queue: 'Live Queue',
    btn_confirm_token: 'Confirm & Generate Digital Token',

    farmer_dashboard_title: 'Farmer Procurement Hub',
    welcome_farmer: 'Welcome back',
    live_token_card: 'Live Active Appointment Token',
    token_now_serving: 'Now Serving Token',
    your_token: 'Your Token Number',
    farmers_ahead: 'Farmers Ahead in Queue',
    est_wait_time: 'Estimated Waiting Time',
    quick_actions: 'Quick Farmer Actions',
    btn_view_token: 'View Digital Token & QR',
    btn_track_queue: 'Track Live Queue',
    btn_procurement_history: 'Procurement History',
    btn_payment_status: 'Payment Status (DBT)',
    btn_book_new_slot: 'Book New Slot',

    digital_pass_title: 'Official Digital Procurement Pass',
    your_digital_token: 'Your Digital Procurement Token',
    verified_qr_pass: 'Verified QR Pass • SmartProcure',
    serving_token: 'Serving Token',
    farmer_label: 'Farmer',
    scheduled_slot: 'Scheduled Slot',
    procurement_hub: 'Procurement Hub',
    live_queue_status: 'Live Queue Status',
    live_queue_ahead: 'ahead in queue',
    btn_download_pass: 'Download Digital Pass (PDF)',
    btn_track_live_queue: 'Track Live Yard Queue',

    queue_tracker_title: 'Real-Time Procurement Queue Tracker',
    now_serving: 'Now Serving',
    in_queue_line: 'In Queue Line',
    queue_progress: 'Queue Progress',
    turn_now: 'Your turn is now!',
    farmers_ahead_count: 'farmers ahead',
    live_queue_flow: 'Live Queue Token Flow',
    dynamic_sync: 'Dynamic Live Sync',
    serving: 'Serving',
    you: 'YOU',
    done: 'Done',
    wait: 'Wait',
    counter1: 'Counter 1',

    stage_arrival: 'Yard Arrival',
    stage_moisture: 'Moisture Testing',
    stage_grading: 'Quality Grading',
    stage_weighing: 'Electronic Weighing',
    stage_voucher: 'Voucher Generation',
    stage_dbt: 'DBT Bank Credit',

    payment_title: 'Direct Benefit Transfer (DBT) Payment Hub',
    total_paid: 'Total Procurement Amount Paid',
    pending_amount: 'Amount in Processing',
    completed_txns: 'Completed Transactions',
    voucher_id: 'Voucher Number',
    bank_status: 'Bank Credit Status',

    footer_text: 'Developed for the Ministry of Consumer Affairs, Food & Public Distribution, Government of India.',
    footer_rights: 'National Agriculture Procurement Portal. All Rights Reserved.'
  },

  te: {
    portal_title: 'స్మార్ట్‌ప్రొక్యూర్',
    govt_title: 'వినియోగదారుల వ్యవహారాలు, ఆహార & ప్రజా పంపిణీ మంత్రిత్వ శాఖ',
    govt_badge: 'ప్రభుత్వ పోర్టల్',
    toll_free: 'ఉచిత కిసాన్ హెల్ప్‌లైన్',
    nav_dashboard: 'డాష్‌బోర్డ్',
    nav_book_slot: 'స్లాట్ బుకింగ్',
    nav_weather: 'వాతావరణ సూచన',
    nav_guidelines: 'తీసుకురావలసిన పత్రాలు',
    nav_my_queue: 'నా క్యూ స్థితి',
    nav_procurement: 'సేకరణ స్థితి',
    nav_payments: 'చెల్లింపులు (DBT)',
    nav_notifications: 'నోటిఫికేషన్లు',
    nav_profile: 'నా ప్రొఫైల్',
    nav_login: 'లాగిన్ / సైన్ ఇన్',
    nav_register: 'కొత్త రిజిస్ట్రేషన్',
    nav_logout: 'లాగౌట్',

    tagline_main: '"స్మార్ట్ క్యూలు. వేగవంతమైన ధాన్యం సేకరణ. రైతుకు మేలు."',
    tagline_desc: 'రైతుల వేచి ఉండే సమయాన్ని తగ్గించి, వాతావరణ సమాచారం, పారదర్శక సేకరణ మరియు తక్షణ చెల్లింపులను అందించే వేదిక.',
    hero_badge: '27+ పంటలు • 16 ప్రాంతీయ కేంద్రాలు • 6 భాషలు',
    btn_farmer_login: 'రైతు లాగిన్',
    btn_officer_login: 'కేంద్ర అధికారి లాగిన్',
    btn_admin_login: 'అడ్మిన్ డాష్‌బోర్డ్',

    stat_crops: '27+ పంటలు',
    stat_crops_sub: 'ధాన్యాలు, పప్పులు, నూనెగింజలు, పత్తి',
    stat_centres: '16 కేంద్రాలు',
    stat_centres_sub: 'అంతర్రాష్ట్ర అనుసంధాన కేంద్రాలు',
    stat_wait_time: '32 నిమిషాలు',
    stat_wait_time_sub: 'సగటు వేచి ఉండే సమయం (65% తగ్గింది)',
    stat_dbt: '100%',
    stat_dbt_sub: 'ప్రత్యక్ష నగదు బదిలీ (DBT)',

    key_features_heading: 'ప్లాట్‌ఫారమ్ ముఖ్య ఫీచర్లు',
    key_features_subheading: 'భారతదేశ వ్యాప్తంగా ధాన్యం సేకరణ కేంద్రాలలో డిజిటల్ సౌలభ్యం, వాతావరణ అంచనా, బహుళ పంటల ఎంపిక, GPS లొకేషన్ మరియు బహుభాషా సౌలభ్యాన్ని అందించడానికి రూపొందించబడింది.',
    feat_multicrop_title: 'బహుళ పంటల స్లాట్ కేటాయింపు',
    feat_multicrop_desc: 'ఒకే టోకెన్‌లో 27+ రకాల పంటలకు (ధాన్యాలు, పప్పులు, నూనెగింజలు, పత్తి, మిరప) ఒకేసారి స్లాట్ బుక్ చేసుకోండి.',
    feat_location_title: 'ఆటో-లొకేషన్ & సమీప సేకరణ కేంద్రాలు',
    feat_location_desc: 'GPS ద్వారా జిల్లాల వారీగా సమీపంలోని ధాన్యం సేకరణ కేంద్రాల దూరాన్ని మరియు లైవ్ క్యూను స్వయంచాలితంగా లెక్కిస్తుంది.',
    feat_language_title: 'బహుభాషా సౌలభ్యం',
    feat_language_desc: 'తెలుగు (తెలుగు), హిందీ (हिन्दी), ఇంగ్లీష్ (English), తమిళం (தமிழ்), కన్నడ (ಕನ್ನಡ) మరియు పంజాబీ (ਪੰਜਾਬੀ) భాషలలో పూర్తి మద్దతు.',
    feat_queue_title: 'లైవ్ క్యూ & వేచి ఉండే సమయం',
    feat_queue_desc: 'యార్డుకు చేరుకోవడానికి ముందే మీ టోకెన్ స్థానం మరియు AI అంచనా వేసిన సమయాన్ని తెలుసుకోండి.',
    feat_pipeline_title: 'సేకరణ ప్రక్రియ లైవ్ ట్రాకింగ్',
    feat_pipeline_desc: 'ధాన్యం రాక నుండి తేమ శాతం పరీక్ష, నాణ్యత గ్రేడింగ్ వరకు 8 దశల ప్రత్యక్ష ప్రక్రియను పర్యవేక్షించండి.',
    feat_dbt_title: 'ప్రత్యక్ష DBT చెల్లింపుల పారదర్శకత',
    feat_dbt_desc: 'ధాన్యం సేకరించిన వెంటనే ప్రభుత్వం నుండి మీ బ్యాంక్ ఖాతాకు జమ అయ్యే DBT నగదు వివరాలను తెలుసుకోండి.',

    how_it_works: 'స్మార్ట్‌ప్రొక్యూర్ ఎలా పనిచేస్తుంది',
    how_desc: 'ఇబ్బంది లేని ధాన్యం సేకరణ కోసం సులభమైన 6 దశల ప్రక్రియ',
    step1_title: 'రిజిస్టర్ / సైన్ ఇన్',
    step1_desc: 'మొబైల్ OTP లేదా రైతు ఐడీతో లాగిన్ అవ్వండి',
    step2_title: 'పంటలను ఎంచుకోండి',
    step2_desc: 'ఒకటి లేదా అంతకంటే ఎక్కువ పంటలను ఎంచుకోండి',
    step3_title: 'సమీప కేంద్రం',
    step3_desc: 'GPS ద్వారా సమీప కేంద్రాన్ని ఎంచుకోండి',
    step4_title: 'టోకెన్ & QR పొందండి',
    step4_desc: 'తక్షణ డిజిటల్ గేట్ పాస్ పొందండి',
    step5_title: 'లైవ్ క్యూ ట్రాకింగ్',
    step5_desc: 'మీ టోకెన్ సమయానికి నేరుగా యార్డుకు చేరుకోండి',
    step6_title: 'తక్షణ DBT నగదు జమ',
    step6_desc: 'MSP చెల్లింపు రశీదు మరియు బ్యాంకు జమ పొందండి',

    ready_cta: 'వేచి ఉండే సమయం లేని సేకరణకు సిద్ధమా?',
    ready_desc: 'బహుళ పంటల స్లాట్ బుక్ చేయండి, వాతావరణ సూచనలు తనిఖీ చేయండి మరియు మార్కెట్ యార్డ్ నిబంధనలను తెలుసుకోండి.',
    btn_launch_booking: 'బహుళ పంటల స్లాట్ బుకింగ్',

    detect_location: 'నా లొకేషన్ గుర్తించు (GPS)',
    location_detected: 'లొకేషన్ గుర్తించబడింది',
    select_location: 'మీ లొకేషన్ / జిల్లా ఎంచుకోండి',
    enter_village: 'గ్రామం / మండలం పేరు',
    enter_address: 'వ్యవసాయ / ఇంటి చిరునామా',
    district_label: 'జిల్లా',
    state_label: 'రాష్ట్రం',
    gps_accuracy: 'GPS ఆధారిత దూరం లెక్కించబడింది',
    near_you: 'మీకు అత్యంత సమీప సేకరణ కేంద్రాలు',

    reg_portal_title: 'రైతు రిజిస్ట్రేషన్ పోర్టల్',
    reg_create_account: 'కొత్త రైతు ఖాతాను సృష్టించండి',
    reg_step1_label: 'వ్యక్తిగత & లొకేషన్ వివరాలు',
    reg_step2_label: 'పంట వివరాలు',
    reg_step3_label: 'సేకరణ కేంద్రం',
    reg_step1_title: 'దశ 1: రైతు గుర్తింపు & లొకేషన్',
    reg_step2_title: 'దశ 2: ప్రధాన పంట & దిగుబడి వివరాలు',
    reg_step3_title: 'దశ 3: ప్రాధాన్య సేకరణ కేంద్రం',
    full_name_label: 'పూర్తి పేరు *',
    name_placeholder: 'ఉదా: రవి కుమార్',
    mobile_placeholder: 'ఉదా: 9876543210',
    village_placeholder: 'ఉదా: పెదకాకాని',
    address_placeholder: 'ఇంటి నంబర్, వీధి పేరు, పిన్‌కోడ్',
    crop_type_label: 'పంట రకం (27+ రకాలు) *',
    variety_label: 'రకం / గ్రేడ్ *',
    variety_placeholder: 'ఉదా: సోనా మసూరి గ్రేడ్ ఎ',
    expected_qty_label: 'అంచనా పరిమాణం (క్వింటాళ్లలో) *',
    qty_helper: '1 క్వింటాల్ = 100 కిలోలు. ప్రభుత్వ కనీస మద్దతు ధర (MSP) వర్తిస్తుంది.',
    centres_matching: 'అందుబాటులో ఉన్న కేంద్రాలు',
    capacity_per_day: 'రోజువారీ సామర్థ్యం',
    btn_prev_step: 'మునుపటి దశ',
    btn_next_step: 'తదుపరి దశ',
    btn_complete_reg: 'రిజిస్ట్రేషన్ పూర్తి చేసి స్లాట్ బుక్ చేయండి',
    already_registered: 'ఇప్పటికే ఖాతా ఉందా? ఇక్కడ సైన్ ఇన్ అవ్వండి',

    signin_title: 'స్మార్ట్‌ప్రొక్యూర్ ఏకీకృత సైన్ ఇన్',
    signin_desc: 'రైతులు, సేకరణ అధికారులు మరియు ప్రభుత్వ అధికారులకు సురక్షిత డిజిటల్ సైన్ ఇన్.',
    tab_farmer: 'రైతు',
    tab_officer: 'అధికారి',
    tab_admin: 'అడ్మిన్',
    farmer_otp_title: 'రైతు మొబైల్ OTP & లొకేషన్ లాగిన్',
    farmer_otp_desc: 'మీ మొబైల్ నంబర్ నమోదు చేసి, మీ జిల్లా/లొకేషన్ ఎంచుకుని OTP పొందండి.',
    mobile_label: 'నమోదిత మొబైల్ నంబర్ / రైతు ID',
    change_mobile: 'మొబైల్ మార్చు',
    enter_otp: '4 అంకెల OTP కోడ్ నమోదు చేయండి',
    otp_hint: 'సూచన: మీ మొబైల్‌కు వచ్చిన 4 అంకెల కోడ్‌ను నమోదు చేయండి',
    resend_otp: 'OTP మళ్లీ పంపు',
    resend_in: 'తిరిగి పంపే సమయం',
    btn_get_otp: 'OTP కోడ్ పొందండి',
    btn_verify_login: 'ధృవీకరించి డాష్‌బోర్డ్‌లోకి ప్రవేశించండి',
    new_farmer_register: 'కొత్త రైతా? ఇక్కడ రిజిస్టర్ అవ్వండి',
    officer_title: 'కేంద్ర అధికారి టెర్మినల్ లాగిన్',
    officer_desc: 'అధీకృత సేకరణ యార్డ్ అధికారులు మరియు కౌంటర్ మేనేజర్ల లాగిన్ పోర్టల్.',
    station_code: 'కేంద్రం / యార్డ్ కోడ్',
    department_password: 'విభాగ పాస్‌వర్డ్',
    btn_officer_login_action: 'అధికారి టెర్మినల్‌లోకి లాగిన్ అవ్వండి',
    admin_title: 'జిల్లా / రాష్ట్ర అడ్మిన్ లాగిన్',
    admin_desc: 'సామర్థ్య నిర్వహణ మరియు విశ్లేషణల కోసం ప్రభుత్వ పాలనా పోర్టల్.',
    admin_id: 'ప్రభుత్వ ఈమెయిల్ / అడ్మిన్ ID',
    security_pin: 'సెక్యూరిటీ పాస్‌కోడ్ / టోకెన్ PIN',
    btn_admin_login_action: 'అడ్మిన్ సూట్‌లోకి ప్రవేశించండి',
    ssl_encrypted: '256-బిట్ SSL ఎన్‌క్రిప్టెడ్',
    aadhaar_integrated: 'ఆధార్ అనుసంధానించబడింది',
    return_home: '← హోమ్ పేజీకి తిరిగి వెళ్ళు',

    slot_booking_title: 'ధాన్యం సేకరణ స్లాట్ బుక్ చేయండి',
    select_crops: 'పంట(లు) ఎంచుకోండి',
    multi_crop_badge: 'బహుళ పంటల ఎంపిక',
    add_crop: 'మరో పంటను జోడించు',
    remove_crop: 'తొలగించు',
    total_quantity: 'మొత్తం పరిమాణం',
    total_est_payout: 'మొత్తం అంచనా MSP విలువ',
    step_crop: '1. పంటలు',
    step_quantity: '2. పరిమాణం',
    step_centre: '3. కేంద్రం',
    step_date: '4. తేదీ',
    step_slot: '5. సమయం',
    step_summary: '6. సారాంశం',
    search_crop_placeholder: 'పంటను వెతకండి (ఉదా: వరి, పత్తి, మిరప, వేరుశనగ)...',
    search_centre_placeholder: 'కేంద్రం లేదా జిల్లా వెతకండి...',
    all_categories: 'అన్ని రకాలు',
    cereals: 'ధాన్యాలు',
    pulses: 'పప్పుధాన్యాలు',
    oilseeds: 'నూనె గింజలు',
    commercial: 'వాణిజ్య పంటలు',
    spices: 'మసాలా పంటలు',
    est_wait: 'అంచనా వేచి ఉండే సమయం',
    live_queue: 'లైవ్ క్యూ',
    btn_confirm_token: 'స్లాట్ నిర్ధారించి డిజిటల్ టోకెన్ పొందండి',

    farmer_dashboard_title: 'రైతు సేకరణ పోర్టల్',
    welcome_farmer: 'స్వాగతం',
    live_token_card: 'లైవ్ అపాయింట్‌మెంట్ టోకెన్',
    token_now_serving: 'ప్రస్తుతం సేవ పొందుతున్న టోకెన్',
    your_token: 'మీ టోకెన్ సంఖ్య',
    farmers_ahead: 'మీ ముందున్న రైతులు',
    est_wait_time: 'అంచనా వేచి ఉండే సమయం',
    quick_actions: 'త్వరిత సేవలు',
    btn_view_token: 'డిజిటల్ టోకెన్ & QR చూడండి',
    btn_track_queue: 'లైవ్ క్యూ ట్రాక్ చేయండి',
    btn_procurement_history: 'సేకరణ చరిత్ర',
    btn_payment_status: 'చెల్లింపు స్థితి (DBT)',
    btn_book_new_slot: 'కొత్త స్లాట్ బుక్ చేయండి',

    digital_pass_title: 'అధికారిక డిజిటల్ సేకరణ పాస్',
    your_digital_token: 'మీ డిజిటల్ సేకరణ టోకెన్',
    verified_qr_pass: 'ధృవీకరించబడిన QR పాస్ • స్మార్ట్‌ప్రొక్యూర్',
    serving_token: 'సేవ పొందుతున్న టోకెన్',
    farmer_label: 'రైతు',
    scheduled_slot: 'కేటాయించిన సమయం',
    procurement_hub: 'సేకరణ కేంద్రం',
    live_queue_status: 'లైవ్ క్యూ స్థితి',
    live_queue_ahead: 'రైతులు మీ ముందున్నారు',
    btn_download_pass: 'డిజిటల్ పాస్ డౌన్‌లోడ్ చేయండి (PDF)',
    btn_track_live_queue: 'లైవ్ యార్డ్ క్యూను ట్రాక్ చేయండి',

    queue_tracker_title: 'రియల్-టైమ్ సేకరణ క్యూ ట్రాకర్',
    now_serving: 'ప్రస్తుతం సేవలో',
    in_queue_line: 'క్యూ లైన్ లో ఉన్నారు',
    queue_progress: 'క్యూ పురోగతి',
    turn_now: 'ఇప్పుడు మీ వంతు వచ్చింది!',
    farmers_ahead_count: 'రైతులు ముందున్నారు',
    live_queue_flow: 'లైవ్ క్యూ టోకెన్ ప్రవాహం',
    dynamic_sync: 'లైవ్ సింక్రొనైజేషన్',
    serving: 'సేవలో',
    you: 'మీరు',
    done: 'పూర్తయింది',
    wait: 'వేచి ఉండండి',
    counter1: 'కౌంటర్ 1',

    stage_arrival: 'యార్డుకు చేరుకోవడం',
    stage_moisture: 'తేమ శాతం పరీక్ష',
    stage_grading: 'నాణ్యత గ్రేడింగ్',
    stage_weighing: 'ఎలక్ట్రానిక్ తూకం',
    stage_voucher: 'రశీదు ఉత్పత్తి',
    stage_dbt: 'బ్యాంకు ఖాతాకు DBT జమ',

    payment_title: 'DBT చెల్లింపుల సమాచార కేంద్రం',
    total_paid: 'ఖాతాలో జమ అయిన మొత్తం సొమ్ము',
    pending_amount: 'ప్రక్రియలో ఉన్న మొత్తం',
    completed_txns: 'పూర్తయిన లావాదేవీలు',
    voucher_id: 'వోచర్ సంఖ్య',
    bank_status: 'బ్యాంక్ జమ స్థితి',

    footer_text: 'భారత ప్రభుత్వ వినియోగదారుల వ్యవహారాలు, ఆహార & ప్రజా పంపిణీ మంత్రిత్వ శాఖ కొరకు రూపొందించబడింది.',
    footer_rights: 'జాతీయ వ్యవసాయ సేకరణ పోర్టల్. సర్వహక్కులు ప్రత్యేకించబడ్డాయి.'
  },

  hi: {
    portal_title: 'स्मार्टप्रोक्योर',
    govt_title: 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय',
    govt_badge: 'सरकारी पोर्टल',
    toll_free: 'टोल-फ्री किसान हेल्पलाइन',
    nav_dashboard: 'डैशबोर्ड',
    nav_book_slot: 'स्लॉट बुक करें',
    nav_weather: 'मौसम पूर्वानुमान',
    nav_guidelines: 'आवश्यक दस्तावेज',
    nav_my_queue: 'मेरी कतार',
    nav_procurement: 'खरीद स्थिति',
    nav_payments: 'भुगतान (DBT)',
    nav_notifications: 'सूचनाएं',
    nav_profile: 'मेरी प्रोफ़ाइल',
    nav_login: 'साइन इन',
    nav_register: 'नया पंजीकरण',
    nav_logout: 'लॉग आउट',

    tagline_main: '"स्मार्ट कतारें। त्वरित खरीद। किसान का उत्थान।"',
    tagline_desc: 'एक आधुनिक डिजिटल खरीद प्रबंधन मंच जो किसानों के प्रतीक्षा समय को कम करता है और मौसम की जानकारी, त्वरित खरीद व पारदर्शी भुगतान प्रदान करता है।',
    hero_badge: '27+ फसलें • 16 क्षेत्रीय केंद्र • 6 भाषाएँ',
    btn_farmer_login: 'किसान लॉगिन',
    btn_officer_login: 'अधिकारी लॉगिन',
    btn_admin_login: 'प्रशासक लॉगिन',

    stat_crops: '27+ फसलें',
    stat_crops_sub: 'अनाज, दालें, तिलहन, कपास व मसाले',
    stat_centres: '16 केंद्र',
    stat_centres_sub: 'अंतर्राज्यीय एकीकृत केंद्र',
    stat_wait_time: '32 मिनट',
    stat_wait_time_sub: 'औसत प्रतीक्षा समय (65% कमी)',
    stat_dbt: '100%',
    stat_dbt_sub: 'प्रत्यक्ष लाभ अंतरण (DBT)',

    key_features_heading: 'प्रमुख मंच सुविधाएं',
    key_features_subheading: 'भारत भर में खरीद केंद्रों में डिजिटल सुविधा, मौसम पूर्वानुमान, बहु-फसल समर्थन, स्थान निकटता और बहुभाषी पहुंच प्रदान करने के लिए निर्मित।',
    feat_multicrop_title: 'बहु-फसल स्लॉट आवंटन',
    feat_multicrop_desc: 'एक ही टोकन में 27+ प्रमुख भारतीय फसलों (अनाज, दालें, तिलहन, कपास, मसाले) के लिए एक साथ स्लॉट बुक करें।',
    feat_location_title: 'ऑटो-स्थान और निकटतम खरीद केंद्र',
    feat_location_desc: 'जीपीएस तकनीक से निकटतम खरीद केंद्रों की सड़क दूरी और कतार की स्थिति तुरंत प्राप्त करें।',
    feat_language_title: 'बहुभाषी पहुंच व सुविधा',
    feat_language_desc: 'अंग्रेजी, तेलुगु (తెలుగు), हिन्दी, तमिल (தமிழ்), कन्नड़ (ಕನ್ನಡ) और पंजाबी (ਪੰਜਾਬੀ) में पूर्ण क्षेत्रीय भाषा समर्थन।',
    feat_queue_title: 'लाइव कतार एवं प्रतीक्षा अनुमान',
    feat_queue_desc: 'यार्ड पहुंचने से पहले ही अपना टोकन नंबर और एआई द्वारा अनुमानित प्रतीक्षा समय जानें।',
    feat_pipeline_title: 'खरीद प्रक्रिया लाइव ट्रैकिंग',
    feat_pipeline_desc: 'उपज के आगमन से लेकर नमी परीक्षण और गुणवत्ता ग्रेडिंग तक 8-चरणीय दृश्य समयरेखा देखें।',
    feat_dbt_title: 'प्रत्यक्ष DBT बैंक भुगतान पारदर्शिता',
    feat_dbt_desc: 'जानिए कि आपकी खरीद राशि डायरेक्ट बेनिफिट ट्रांसफर (DBT) के माध्यम से सीधे आपके बैंक खाते में कब जमा हुई।',

    how_it_works: 'स्मार्टप्रोक्योर कैसे काम करता है',
    how_desc: 'सुगम और पारदर्शी खरीद के लिए 6-चरणीय सरल प्रक्रिया',
    step1_title: 'पंजीकरण / लॉगिन',
    step1_desc: 'मोबाइल OTP या किसान आईडी से लॉगिन करें',
    step2_title: 'फसलें चुनें',
    step2_desc: 'एक या अधिक फसलों का चयन करें',
    step3_title: 'निकटतम केंद्र',
    step3_desc: 'जीपीएस द्वारा निकटतम केंद्र चुनें',
    step4_title: 'टोकन व क्यूआर प्राप्त करें',
    step4_desc: 'डिजिटल अपॉइंटमेंट पास प्राप्त करें',
    step5_title: 'लाइव कतार ट्रैकिंग',
    step5_desc: 'टोकन पुकारने पर समय पर पहुंचें',
    step6_title: 'तुरंत DBT बैंक भुगतान',
    step6_desc: 'MSP वाउचर और बैंक खाता क्रेडिट प्राप्त करें',

    ready_cta: 'शून्य प्रतीक्षा खरीद का अनुभव लेने के लिए तैयार हैं?',
    ready_desc: 'मल्टी-क्रॉप डिलीवरी स्लॉट बुक करें, मौसम का पूर्वानुमान देखें और केंद्र आगमन चेकलिस्ट जांचें।',
    btn_launch_booking: 'मल्टी-क्रॉप बुकिंग शुरू करें',

    detect_location: 'मेरा स्थान पहचानें (GPS)',
    location_detected: 'स्थान प्राप्त हुआ',
    select_location: 'अपना स्थान / जिला चुनें',
    enter_village: 'गाँव / मंडल का नाम',
    enter_address: 'खेत / निवास का पता',
    district_label: 'ज़िला',
    state_label: 'राज्य',
    gps_accuracy: 'GPS निकटता की गणना की गई',
    near_you: 'आपके निकटतम खरीद केंद्र',

    reg_portal_title: 'किसान पंजीकरण पोर्टल',
    reg_create_account: 'नया किसान खाता बनाएं',
    reg_step1_label: 'व्यक्तिगत एवं स्थान विवरण',
    reg_step2_label: 'फसल विवरण',
    reg_step3_label: 'खरीद केंद्र',
    reg_step1_title: 'चरण 1: किसान पहचान एवं स्थान',
    reg_step2_title: 'चरण 2: मुख्य फसल एवं उपज विवरण',
    reg_step3_title: 'चरण 3: पसंदीदा खरीद केंद्र',
    full_name_label: 'पूरा नाम *',
    name_placeholder: 'उदा. रवि कुमार',
    mobile_placeholder: 'उदा. 9876543210',
    village_placeholder: 'उदा. पेदाकाकानी',
    address_placeholder: 'मकान नंबर, सड़क, पिनकोड',
    crop_type_label: 'फसल का प्रकार (27+ विकल्प) *',
    variety_label: 'किस्म / ग्रेड *',
    variety_placeholder: 'उदा. सोना मसूरी ग्रेड ए',
    expected_qty_label: 'अनुमानित मात्रा (क्विंटल में) *',
    qty_helper: '1 क्विंटल = 100 किलोग्राम। सरकारी न्यूनतम समर्थन मूल्य (MSP) लागू।',
    centres_matching: 'उपलब्ध खरीद केंद्र',
    capacity_per_day: 'दैनिक क्षमता',
    btn_prev_step: 'पिछला चरण',
    btn_next_step: 'अगला चरण',
    btn_complete_reg: 'पंजीकरण पूर्ण करें व स्लॉट बुक करें',
    already_registered: 'पहले से पंजीकृत हैं? यहाँ साइन इन करें',

    signin_title: 'स्मार्टप्रोक्योर एकीकृत साइन इन',
    signin_desc: 'किसानों, खरीद अधिकारियों और सरकारी अधिकारियों के लिए सुरक्षित डिजिटल साइन इन।',
    tab_farmer: 'किसान',
    tab_officer: 'अधिकारी',
    tab_admin: 'प्रशासक',
    farmer_otp_title: 'किसान मोबाइल OTP एवं स्थान लॉगिन',
    farmer_otp_desc: 'अपना मोबाइल नंबर दर्ज करें, अपना जिला/स्थान चुनें और OTP प्राप्त करें।',
    mobile_label: 'पंजीकृत मोबाइल नंबर / किसान आईडी',
    change_mobile: 'मोबाइल बदलें',
    enter_otp: '4 अंकों का OTP कोड दर्ज करें',
    otp_hint: 'संकेत: अपने मोबाइल पर प्राप्त 4 अंकों का कोड दर्ज करें',
    resend_otp: 'OTP पुनः भेजें',
    resend_in: 'पुनः भेजने का समय',
    btn_get_otp: 'OTP कोड प्राप्त करें',
    btn_verify_login: 'सत्यापित करें और डैशबोर्ड खोलें',
    new_farmer_register: 'नए किसान? यहाँ पंजीकरण करें',
    officer_title: 'केंद्र अधिकारी टर्मिनल लॉगिन',
    officer_desc: 'अधिकृत खरीद यार्ड अधिकारियों और काउंटर प्रबंधकों का लॉगिन पोर्टल।',
    station_code: 'केंद्र / यार्ड कोड',
    department_password: 'विभागीय पासवर्ड',
    btn_officer_login_action: 'अधिकारी टर्मिनल में लॉगिन करें',
    admin_title: 'जिला / राज्य प्रशासक लॉगिन',
    admin_desc: 'क्षमता प्रबंधन और विश्लेषण के लिए सरकारी प्रशासन पोर्टल।',
    admin_id: 'सरकारी ईमेल / एडमिन आईडी',
    security_pin: 'सुरक्षा पासकोड / टोकन पिन',
    btn_admin_login_action: 'एडमिन सूट में प्रवेश करें',
    ssl_encrypted: '256-बिट एसएसएल एन्क्रिप्टेड',
    aadhaar_integrated: 'आधार एकीकृत',
    return_home: '← मुख्य पृष्ठ पर लौटें',

    slot_booking_title: 'उपज खरीद स्लॉट बुक करें',
    select_crops: 'फसल(एं) चुनें',
    multi_crop_badge: 'बहु-फसल चयन',
    add_crop: 'एक और फसल जोड़ें',
    remove_crop: 'हटाएं',
    total_quantity: 'कुल मात्रा',
    total_est_payout: 'अनुमानित कुल MSP भुगतान',
    step_crop: '1. फसलें',
    step_quantity: '2. मात्रा',
    step_centre: '3. केंद्र',
    step_date: '4. दिनांक',
    step_slot: '5. समय',
    step_summary: '6. विवरण',
    search_crop_placeholder: 'फसल खोजें (जैसे धान, गेहूं, कपास, सरसों, चना)...',
    search_centre_placeholder: 'केंद्र या जिला खोजें...',
    all_categories: 'सभी श्रेणियां',
    cereals: 'अनाज एवं खाद्यान्न',
    pulses: 'दालें',
    oilseeds: 'तिलहन',
    commercial: 'व्यावसायिक फसलें',
    spices: 'मसाले',
    est_wait: 'अनुमानित प्रतीक्षा',
    live_queue: 'लाइव कतार',
    btn_confirm_token: 'पुष्टि करें और डिजिटल टोकन प्राप्त करें',

    farmer_dashboard_title: 'किसान खरीद पोर्टल',
    welcome_farmer: 'स्वागत है',
    live_token_card: 'सक्रिय अपॉइंटमेंट टोकन',
    token_now_serving: 'वर्तमान में सेवारत टोकन',
    your_token: 'आपका टोकन नंबर',
    farmers_ahead: 'कतार में आगे किसान',
    est_wait_time: 'अनुमानित प्रतीक्षा समय',
    quick_actions: 'त्वरित कार्य',
    btn_view_token: 'डिजिटल टोकन व क्यूआर देखें',
    btn_track_queue: 'लाइव कतार ट्रैक करें',
    btn_procurement_history: 'खरीद इतिहास',
    btn_payment_status: 'भुगतान स्थिति (DBT)',
    btn_book_new_slot: 'नया स्लॉट बुक करें',

    digital_pass_title: 'आधिकारिक डिजिटल खरीद पास',
    your_digital_token: 'आपका डिजिटल खरीद टोकन',
    verified_qr_pass: 'सत्यापित क्यूआर पास • स्मार्टप्रोक्योर',
    serving_token: 'वर्तमान टोकन',
    farmer_label: 'किसान',
    scheduled_slot: 'निर्धारित समय',
    procurement_hub: 'खरीद केंद्र',
    live_queue_status: 'लाइव कतार स्थिति',
    live_queue_ahead: 'किसान आगे कतार में हैं',
    btn_download_pass: 'डिजिटल पास डाउनलोड करें (PDF)',
    btn_track_live_queue: 'लाइव यार्ड कतार ट्रैक करें',

    queue_tracker_title: 'रीयल-टाइम खरीद कतार ट्रैकर',
    now_serving: 'वर्तमान में सेवारत',
    in_queue_line: 'कतार में',
    queue_progress: 'कतार की प्रगति',
    turn_now: 'अब आपकी बारी है!',
    farmers_ahead_count: 'किसान आगे हैं',
    live_queue_flow: 'लाइव कतार प्रवाह',
    dynamic_sync: 'लाइव सिंक',
    serving: 'सेवारत',
    you: 'आप',
    done: 'पूर्ण',
    wait: 'प्रतीक्षा',
    counter1: 'काउंटर 1',

    stage_arrival: 'यार्ड आगमन',
    stage_moisture: 'नमी परीक्षण',
    stage_grading: 'गुणवत्ता ग्रेडिंग',
    stage_weighing: 'इलेक्ट्रॉनिक वजन',
    stage_voucher: 'रसीद जारी',
    stage_dbt: 'डीबीटी बैंक क्रेडिट',

    payment_title: 'डीबीटी भुगतान सूचना केंद्र',
    total_paid: 'खाते में प्राप्त कुल राशि',
    pending_amount: 'प्रक्रियाधीन राशि',
    completed_txns: 'सफल लेनदेन',
    voucher_id: 'वाउचर संख्या',
    bank_status: 'बैंक जमा स्थिति',

    footer_text: 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय, भारत सरकार के लिए विकसित।',
    footer_rights: 'राष्ट्रीय कृषि खरीद पोर्टल। सर्वाधिकार सुरक्षित।'
  },

  ta: {
    portal_title: 'ஸ்மார்ட் ப்ரோக்யூர்',
    govt_title: 'நுகர்வோர் விவகாரங்கள், உணவு மற்றும் பொது விநியோக அமைச்சகம்',
    govt_badge: 'அரசு போர்டல்',
    toll_free: 'இலவச உழவர் உதவி எண்',
    nav_dashboard: 'டாஷ்போர்டு',
    nav_book_slot: 'முன்பதிவு செய்',
    nav_weather: 'வானிலை முன்னறிவிப்பு',
    nav_guidelines: 'தேவையான ஆவணங்கள்',
    nav_my_queue: 'என் வரிசை',
    nav_procurement: 'கொள்முதல்',
    nav_payments: 'பணம் செலுத்துதல் (DBT)',
    nav_notifications: 'அறிவிப்புகள்',
    nav_profile: 'சுயவிவரம்',
    nav_login: 'உள்நுழைக',
    nav_register: 'பதிவு செய்க',
    nav_logout: 'வெளியேறு',

    tagline_main: '"ஸ்மார்ட் வரிசைகள். விரைவான கொள்முதல். சிறந்த விவசாயம்."',
    tagline_desc: 'விவசாயிகளின் காத்திருப்பு நேரத்தைக் குறைத்து வானிலை தகவல் மற்றும் வெளிப்படையான வங்கி பரிவர்த்தனைகளை வழங்கும் டிஜிட்டல் தளம்.',
    hero_badge: '27+ பயிர்கள் • 16 மையங்கள் • 6 மொழிகள்',
    btn_farmer_login: 'விவசாயி உள்நுழைவு',
    btn_officer_login: 'அதிகாரி உள்நுழைவு',
    btn_admin_login: 'நிர்வாகி உள்நுழைவு',

    stat_crops: '27+ பயிர்கள்',
    stat_crops_sub: 'தானியங்கள், பருப்பு, எண்ணெய் வித்துக்கள்',
    stat_centres: '16 மையங்கள்',
    stat_centres_sub: 'மாநில அளவிலான மையங்கள்',
    stat_wait_time: '32 நிமிடம்',
    stat_wait_time_sub: 'சராசரி காத்திருப்பு நேரம் (65% குறைவு)',
    stat_dbt: '100%',
    stat_dbt_sub: 'நேரடி வங்கி பரிமாற்றம் (DBT)',

    key_features_heading: 'தளத்தின் முக்கிய அம்சங்கள்',
    key_features_subheading: 'இந்தியா முழுவதும் உள்ள கொள்முதல் நிலையங்களில் டிஜிட்டல் வசதி, பல பயிர் தேர்வு, வானிலை முன்னறிவிப்பு மற்றும் பல மொழி சேவைகளை வழங்க வடிவமைக்கப்பட்டுள்ளது.',
    feat_multicrop_title: 'பல பயிர் நேர ஒதுக்கீடு',
    feat_multicrop_desc: 'ஒரே டிக்கெட்டில் 27+ பயிர்களுக்கு (தானியங்கள், பருப்பு வகைகள், எண்ணெய் வித்துக்கள், பருத்தி) முன்பதிவு செய்யுங்கள்.',
    feat_location_title: 'தானியங்கி இருப்பிடம் மற்றும் அருகிலுள்ள நிலையங்கள்',
    feat_location_desc: 'ஜிபிஎஸ் மூலம் அருகிலுள்ள கொள்முதல் நிலையங்களின் தூரத்தை உடனடியாக கணக்கிடுங்கள்.',
    feat_language_title: 'பல மொழி அணுகல்தன்மை',
    feat_language_desc: 'ஆங்கிலம், தமிழ், தெலுங்கு, இந்தி, கன்னடம் மற்றும் பஞ்சாபி மொழிகளில் முழுமையான ஆதரவு.',
    feat_queue_title: 'நேரடி வரிசை & காத்திருப்பு நேரம்',
    feat_queue_desc: 'நிலையத்திற்கு வருவதற்கு முன்பே உங்கள் டோக்கன் எண் மற்றும் காத்திருப்பு நேரத்தை அறியுங்கள்.',
    feat_pipeline_title: 'கொள்முதல் செயல்முறை கண்காணிப்பு',
    feat_pipeline_desc: 'தானிய வரவு முதல் ஈரப்பத சோதனை மற்றும் தரம் பிரித்தல் வரை 8-படி காலவரிசையைக் கண்காணிக்கவும்.',
    feat_dbt_title: 'நேரடி DBT வங்கி பரிவர்த்தனை',
    feat_dbt_desc: 'கொள்முதல் தொகை எப்போது உங்கள் வங்கிக் கணக்கில் நேரடியாக வரவு வைக்கப்பட்டது என்பதை அறியுங்கள்.',

    how_it_works: 'இது எவ்வாறு செயல்படுகிறது',
    how_desc: 'எளிய 6-படி கொள்முதல் செயல்முறை',
    step1_title: 'பதிவு / உள்நுழைவு',
    step1_desc: 'மொபைல் OTP மூலம் உள்நுழையவும்',
    step2_title: 'பயிர்களைத் தேர்வு செய்',
    step2_desc: 'ஒன்று அல்லது அதற்கு மேற்பட்ட பயிர்களைத் தேர்ந்தெடுக்கவும்',
    step3_title: 'அருகிலுள்ள மையம்',
    step3_desc: 'ஜிபிஎஸ் மூலம் அருகிலுள்ள மையத்தைக் கண்டறியவும்',
    step4_title: 'டோக்கன் & QR பெறவும்',
    step4_desc: 'டிஜிட்டல் அனுமதிச் சீட்டைப் பெறுங்கள்',
    step5_title: 'நேரடி வரிசை கண்காணிப்பு',
    step5_desc: 'டோக்கன் அறிவிப்பின்படி வருகை தரவும்',
    step6_title: 'வங்கி கணக்கில் வரவு',
    step6_desc: 'வங்கி பரிமாற்ற ரசீதைப் பெறுங்கள்',

    ready_cta: 'விரைவான கொள்முதல் சேவையை பெற தயாரா?',
    ready_desc: 'பல்வேறு பயிர்களுக்கான நேரத்தை முன்பதிவு செய்து வானிலை முன்னறிவிப்பு மற்றும் கொள்முதல் ஆவணங்களை சரிபார்க்கவும்.',
    btn_launch_booking: 'முன்பதிவை தொடங்கு',

    detect_location: 'என் இருப்பிடத்தைக் கண்டறி (GPS)',
    location_detected: 'இருப்பிடம் கண்டறியப்பட்டது',
    select_location: 'உங்கள் மாவட்டம் / பகுதியைத் தேர்ந்தெடுக்கவும்',
    enter_village: 'கிராமம் / தாலுகா பெயர்',
    enter_address: 'விவசாய நிலம் / முகவரி',
    district_label: 'மாவட்டம்',
    state_label: 'மாநிலம்',
    gps_accuracy: 'ஜிபிஎஸ் தூரம் கணக்கிடப்பட்டது',
    near_you: 'உங்களுக்கு அருகிலுள்ள கொள்முதல் நிலையங்கள்',

    reg_portal_title: 'விவசாயி பதிவு போர்டல்',
    reg_create_account: 'புதிய விவசாயி கணக்கை உருவாக்கவும்',
    reg_step1_label: 'தனிப்பட்ட & இருப்பிட விவரங்கள்',
    reg_step2_label: 'பயிர் விவரங்கள்',
    reg_step3_label: 'கொள்முதல் மையம்',
    reg_step1_title: 'படி 1: விவசாயி அடையாளம் & இருப்பிடம்',
    reg_step2_title: 'படி 2: முதன்மைப் பயிர் விவரங்கள்',
    reg_step3_title: 'படி 3: விருப்பமான கொள்முதல் மையம்',
    full_name_label: 'முழுப் பெயர் *',
    name_placeholder: 'எ.கா. ரவி குமார்',
    mobile_placeholder: 'எ.கா. 9876543210',
    village_placeholder: 'எ.கா. பெடகாகானி',
    address_placeholder: 'கதவு எண், தெரு, பின்கோடு',
    crop_type_label: 'பயிர் வகை (27+ தேர்வுகள்) *',
    variety_label: 'வகை / தரம் *',
    variety_placeholder: 'எ.கா. சோனா மசூரி கிரேடு ஏ',
    expected_qty_label: 'எதிர்பார்க்கப்படும் அளவு (குவிண்டாலில்) *',
    qty_helper: '1 குவிண்டால் = 100 கிலோ. அரசு குறைந்தபட்ச ஆதரவு விலை (MSP) பொருந்தும்.',
    centres_matching: 'கிடைக்கும் மையங்கள்',
    capacity_per_day: 'தினசரி திறன்',
    btn_prev_step: 'முந்தைய படி',
    btn_next_step: 'அடுத்த படி',
    btn_complete_reg: 'பதிவை முடித்து முன்பதிவு செய்யவும்',
    already_registered: 'ஏற்கனவே பதிவு செய்துள்ளீர்களா? உள்நுழைக',

    signin_title: 'ஸ்மார்ட் ப்ரோக்யூர் ஒருங்கிணைந்த உள்நுழைவு',
    signin_desc: 'விவசாயிகள் மற்றும் அரசு அதிகாரிகளுக்கான பாதுகாப்பான உள்நுழைவு தளம்.',
    tab_farmer: 'விவசாயி',
    tab_officer: 'அதிகாரி',
    tab_admin: 'நிர்வாகி',
    farmer_otp_title: 'விவசாயி மொபைல் OTP & இருப்பிட உள்நுழைவு',
    farmer_otp_desc: 'உங்கள் மொபைல் எண் மற்றும் மாவட்டத்தைத் தேர்ந்தெடுத்து OTP பெறுங்கள்.',
    mobile_label: 'பதிவு செய்யப்பட்ட மொபைல் எண்',
    change_mobile: 'எண்ணை மாற்று',
    enter_otp: '4 இலக்க OTP குறியீட்டை உள்ளிடவும்',
    otp_hint: 'குறிப்பு: உங்கள் மொபைலுக்கு அனுப்பப்பட்ட 4 இலக்க குறியீட்டை உள்ளிடவும்',
    resend_otp: 'OTP மீண்டும் அனுப்புக',
    resend_in: 'மீண்டும் அனுப்பும் நேரம்',
    btn_get_otp: 'OTP குறியீட்டைப் பெறுங்கள்',
    btn_verify_login: 'சரிபார்த்து உள்நுழைக',
    new_farmer_register: 'புதிய விவசாயியா? பதிவு செய்க',
    officer_title: 'அதிகாரி டெர்மினல் உள்நுழைவு',
    officer_desc: 'கொள்முதல் மைய அதிகாரிகளுக்கான பிரத்யேக தளம்.',
    station_code: 'மையக் குறியீடு',
    department_password: 'கடவுச்சொல்',
    btn_officer_login_action: 'அதிகாரி தளத்தில் உள்நுழைக',
    admin_title: 'நிர்வாகி உள்நுழைவு',
    admin_desc: 'அரசு மேற்பார்வை மற்றும் பகுப்பாய்வு தளம்.',
    admin_id: 'அரசு மின்னஞ்சல் / ஐடி',
    security_pin: 'பாதுகாப்பு பின் குறியீடு',
    btn_admin_login_action: 'நிர்வாக தளத்தில் உள்நுழைக',
    ssl_encrypted: '256-பிட் SSL பாதுகாப்பு',
    aadhaar_integrated: 'ஆதார் இணைக்கப்பட்டது',
    return_home: '← முதன்மைப் பக்கத்திற்கு செல்',

    slot_booking_title: 'கொள்முதல் நேரத்தை முன்பதிவு செய்',
    select_crops: 'பயிர்களைத் தேர்ந்தெடுக்கவும்',
    multi_crop_badge: 'பல பயிர் தேர்வு',
    add_crop: 'மற்றொரு பயிரைச் சேர்',
    remove_crop: 'நீக்கு',
    total_quantity: 'மொத்த அளவு',
    total_est_payout: 'மொத்த எதிர்பார்க்கப்படும் தொகை',
    step_crop: '1. பயிர்கள்',
    step_quantity: '2. அளவு',
    step_centre: '3. மையம்',
    step_date: '4. தேதி',
    step_slot: '5. நேரம்',
    step_summary: '6. சுருக்கம்',
    search_crop_placeholder: 'பயிரைத் தேடுங்கள் (நெல், பருத்தி, கரும்பு, நிலக்கடலை)...',
    search_centre_placeholder: 'மையம் அல்லது மாவட்டத்தைத் தேடுங்கள்...',
    all_categories: 'அனைத்து பிரிவுகள்',
    cereals: 'தானியங்கள்',
    pulses: 'பருப்பு வகைகள்',
    oilseeds: 'எண்ணெய் வித்துக்கள்',
    commercial: 'வணிகப் பயிர்கள்',
    spices: 'மசாலாப் பொருட்கள்',
    est_wait: 'காத்திருப்பு நேரம்',
    live_queue: 'நேரடி வரிசை',
    btn_confirm_token: 'டோக்கனைப் பெறுங்கள்',

    farmer_dashboard_title: 'விவசாயி கொள்முதல் தளம்',
    welcome_farmer: 'நல்வரவு',
    live_token_card: 'செயலில் உள்ள டோக்கன்',
    token_now_serving: 'தற்போது பரிசீலிக்கப்படும் டோக்கன்',
    your_token: 'உங்கள் டோக்கன் எண்',
    farmers_ahead: 'உங்களுக்கு முன் உள்ள விவசாயிகள்',
    est_wait_time: 'மதிப்பிடப்பட்ட காத்திருப்பு நேரம்',
    quick_actions: 'விரைவு சேவைகள்',
    btn_view_token: 'டிஜிட்டல் டோக்கன் பார்க்க',
    btn_track_queue: 'வரிசையை கண்காணிக்க',
    btn_procurement_history: 'கொள்முதல் வரலாறு',
    btn_payment_status: 'வங்கி பரிமாற்ற நிலை',
    btn_book_new_slot: 'புதிய முன்பதிவு செய்ய',

    digital_pass_title: 'அதிகாரப்பூர்வ டிஜிட்டல் அனுமதிச் சீட்டு',
    your_digital_token: 'உங்கள் டிஜிட்டல் டோக்கன்',
    verified_qr_pass: 'சரிபார்க்கப்பட்ட QR பாஸ் • ஸ்மார்ட் ப்ரோக்யூர்',
    serving_token: 'தற்போதைய டோக்கன்',
    farmer_label: 'விவசாயி',
    scheduled_slot: 'முன்பதிவு நேரம்',
    procurement_hub: 'கொள்முதல் மையம்',
    live_queue_status: 'நேரடி வரிசை நிலை',
    live_queue_ahead: 'விவசாயிகள் முன்னால் உள்ளனர்',
    btn_download_pass: 'டிஜிட்டல் பாஸை பதிவிறக்கவும் (PDF)',
    btn_track_live_queue: 'நேரடி வரிசையை கண்காணிக்கவும்',

    queue_tracker_title: 'நேரடி வரிசை கண்காணிப்பு',
    now_serving: 'தற்போது பரிசீலிக்கப்படுகிறது',
    in_queue_line: 'வரிசையில்',
    queue_progress: 'வரிசை முன்னேற்றம்',
    turn_now: 'இப்போது உங்கள் முறை!',
    farmers_ahead_count: 'விவசாயிகள் முன்னால்',
    live_queue_flow: 'நேரடி டோக்கன் ஓட்டம்',
    dynamic_sync: 'நேரடி இணைப்பு',
    serving: 'பரிசீலனை',
    you: 'நீங்கள்',
    done: 'முடிந்தது',
    wait: 'காத்திருக்கவும்',
    counter1: 'கவுண்டர் 1',

    stage_arrival: 'நிலையம் வருதல்',
    stage_moisture: 'ஈரப்பத பரிசோதனை',
    stage_grading: 'தரம் பிரித்தல்',
    stage_weighing: 'எடை போடுதல்',
    stage_voucher: 'ரசீது உருவாக்கம்',
    stage_dbt: 'வங்கி கணக்கில் வரவு',

    payment_title: 'DBT வங்கி பரிவர்த்தனை மையம்',
    total_paid: 'கணக்கில் பெறப்பட்ட தொகை',
    pending_amount: 'செயல்பாட்டில் உள்ள தொகை',
    completed_txns: 'வெற்றிகரமான பரிவர்த்தனைகள்',
    voucher_id: 'ரசீது எண்',
    bank_status: 'வங்கி வரவு நிலை',

    footer_text: 'இந்திய அரசின் நுகர்வோர் விவகாரங்கள், உணவு மற்றும் பொது விநியோக அமைச்சகத்திற்காக உருவாக்கப்பட்டது.',
    footer_rights: 'தேசிய வேளாண் கொள்முதல் போர்டல். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.'
  },

  kn: {
    portal_title: 'ಸ್ಮಾರ್ಟ್‌ಪ್ರೊಕ್ಯೂರ್',
    govt_title: 'ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳು, ಆಹಾರ ಮತ್ತು ಸಾರ್ವಜನಿಕ ವಿತರಣಾ ಸಚಿವಾಲಯ',
    govt_badge: 'ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್',
    toll_free: 'ಉಚಿತ ಕಿಸಾನ್ ಸಹಾಯವಾಣಿ',
    nav_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    nav_book_slot: 'ಸ್ಲಾಟ್ ಬುಕಿಂಗ್',
    nav_weather: 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    nav_guidelines: 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
    nav_my_queue: 'ನನ್ನ ಸರತಿ ಸಾಲು',
    nav_procurement: 'ಖರೀದಿ ಸ್ಥಿತಿ',
    nav_payments: 'ಪಾವತಿಗಳು (DBT)',
    nav_notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    nav_profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    nav_login: 'ಲಾಗಿನ್',
    nav_register: 'ನೋಂದಣಿ',
    nav_logout: 'ಲಾಗ್‌ಔಟ್',

    tagline_main: '"ಸ್ಮಾರ್ಟ್ ಸಾಲುಗಳು. ವೇಗದ ಖರೀದಿ. ರೈತರಿಗೆ ಅನುಕೂಲ."',
    tagline_desc: 'ರೈತರ ಕಾಯುವ ಸಮಯವನ್ನು ಕಡಿಮೆ ಮಾಡುವ, ಹವಾಮಾನ ಮಾಹಿತಿ ಮತ್ತು ಪಾರದರ್ಶಕತೆ ಹೆಚ್ಚಿಸುವ ಸುಧಾರಿತ ಡಿಜಿಟಲ್ ವೇದಿಕೆ.',
    hero_badge: '27+ ಬೆಳೆಗಳು • 16 ಕೇಂದ್ರಗಳು • 6 ಭಾಷೆಗಳು',
    btn_farmer_login: 'ರೈತ ಲಾಗಿನ್',
    btn_officer_login: 'ಅಧಿಕಾರಿ ಲಾಗಿನ್',
    btn_admin_login: 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',

    stat_crops: '27+ ಬೆಳೆಗಳು',
    stat_crops_sub: 'ಧಾನ್ಯಗಳು, ಬೇಳೆಕಾಳುಗಳು, ಎಣ್ಣೆಕಾಳುಗಳು',
    stat_centres: '16 ಕೇಂದ್ರಗಳು',
    stat_centres_sub: 'ರಾಜ್ಯಾದ್ಯಂತ ಕೇಂದ್ರಗಳು',
    stat_wait_time: '32 ನಿಮಿಷ',
    stat_wait_time_sub: 'ಸರಾಸರಿ ಕಾಯುವ ಸಮಯ (65% ಕಡಿಮೆ)',
    stat_dbt: '100%',
    stat_dbt_sub: 'ನೇರ ನಗದು ಜಮೆ (DBT)',

    key_features_heading: 'ವೇದಿಕೆಯ ಪ್ರಮುಖ ವೈಶಿಷ್ಟ್ಯಗಳು',
    key_features_subheading: 'ಭಾರತದಾದ್ಯಂತ ಖರೀದಿ ಕೇಂದ್ರಗಳಲ್ಲಿ ಡಿಜಿಟಲ್ ಸೌಲಭ್ಯ, ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ, ಬಹು ಬೆಳೆ ಬೆಂಬಲ, ಸ್ಥಳ ಸಾಮೀಪ್ಯ ಮತ್ತು ಬಹುಭಾಷಾ ಸೌಲಭ್ಯ ಒದಗಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.',
    feat_multicrop_title: 'ಬಹು ಬೆಳೆ ಸ್ಲಾಟ್ ಹಂಚಿಕೆ',
    feat_multicrop_desc: 'ಒಂದೇ ಟಿಕೆಟ್‌ನಲ್ಲಿ 27+ ಬೆಳೆಗಳಿಗೆ (ಧಾನ್ಯಗಳು, ಬೇಳೆಕಾಳುಗಳು, ಎಣ್ಣೆಕಾಳುಗಳು, ಹತ್ತಿ) ಏಕಕಾಲದಲ್ಲಿ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ.',
    feat_location_title: 'ಸ್ವಯಂ ಸ್ಥಳ ಮತ್ತು ಹತ್ತಿರದ ಕೇಂದ್ರಗಳು',
    feat_location_desc: 'ಜಿಪಿಎಸ್ ಮೂಲಕ ಹತ್ತಿರದ ಖರೀದಿ ಕೇಂದ್ರಗಳ ಅಂತರವನ್ನು ಮತ್ತು ಸರತಿ ಸಾಲನ್ನು ತಕ್ಷಣ ಲೆಕ್ಕಹಾಕಿ.',
    feat_language_title: 'ಬಹುಭಾಷಾ ಪ್ರವೇಶಿಸುವಿಕೆ',
    feat_language_desc: 'ಇಂಗ್ಲಿಷ್, ಕನ್ನಡ, ತೆಲುಗು, ಹಿಂದಿ, ತಮಿಳು ಮತ್ತು ಪಂಜಾಬಿ ಭಾಷೆಗಳಲ್ಲಿ ಸಂಪೂರ್ಣ ಪ್ರಾದೇಶಿಕ ಭಾಷಾ ಬೆಂಬಲ.',
    feat_queue_title: 'ಲೈವ್ ಸಾಲು & ಕಾಯುವ ಸಮಯ',
    feat_queue_desc: 'ಕೇಂದ್ರಕ್ಕೆ ಬರುವ ಮೊದಲೇ ನಿಮ್ಮ ಟೋಕನ್ ಸ್ಥಾನ ಮತ್ತು ಅಂದಾಜು ಕಾಯುವ ಸಮಯವನ್ನು ತಿಳಿಯಿರಿ.',
    feat_pipeline_title: 'ಖರೀದಿ ಪ್ರಕ್ರಿಯೆ ಟ್ರ್ಯಾಕಿಂಗ್',
    feat_pipeline_desc: 'ಬೆಳೆ ಆಗಮನದಿಂದ ತೇವಾಂಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಗುಣಮಟ್ಟ ಶ್ರೇಣೀಕರಣದವರೆಗೆ 8-ಹಂತದ ಪ್ರಕ್ರಿಯೆ ವೀಕ್ಷಿಸಿ.',
    feat_dbt_title: 'ನೇರ DBT ಬ್ಯಾಂಕ್ ಪಾವತಿ ಪಾರದರ್ಶಕತೆ',
    feat_dbt_desc: 'ನಿಮ್ಮ ಬೆಳೆಯ ಹಣ ಯಾವಾಗ ನೇರವಾಗಿ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗಿದೆ ಎಂಬುದನ್ನು ತಕ್ಷಣ ತಿಳಿಯಿರಿ.',

    how_it_works: 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    how_desc: 'ಸರಳ 6 ಹಂತಗಳ ಬೆಳೆ ಖರೀದಿ ಪ್ರಕ್ರಿಯೆ',
    step1_title: 'ನೋಂದಣಿ / ಲಾಗಿನ್',
    step1_desc: 'ಮೊಬೈಲ್ OTP ಮೂಲಕ ಲಾಗಿನ್ ಮಾಡಿ',
    step2_title: 'ಬೆಳೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    step2_desc: 'ಒಂದು ಅಥವಾ ಹೆಚ್ಚಿನ ಬೆಳೆಗಳನ್ನು ಆರಿಸಿ',
    step3_title: 'ಹತ್ತಿರದ ಕೇಂದ್ರ',
    step3_desc: 'ಜಿಪಿಎಸ್ ಮೂಲಕ ಹತ್ತಿರದ ಕೇಂದ್ರ ಆಯ್ಕೆಮಾಡಿ',
    step4_title: 'ಟೋಕನ್ & QR ಪಡೆಯಿರಿ',
    step4_desc: 'ಡಿಜಿಟಲ್ ಗೇಟ್ ಪಾಸ್ ಪಡೆಯಿರಿ',
    step5_title: 'ಲೈವ್ ಸಾಲು ಟ್ರ್ಯಾಕಿಂಗ್',
    step5_desc: 'ಟೋಕನ್ ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ ತಲುಪಿ',
    step6_title: 'ನೇರ ಬ್ಯಾಂಕ್ ಜಮೆ',
    step6_desc: 'ಎಂಎಸ್‌ಪಿ ಪಾವತಿ ರಶೀದಿ ಪಡೆಯಿರಿ',

    ready_cta: 'ವೇಗದ ಬೆಳೆ ಖರೀದಿಗೆ ಸಿದ್ಧರಿದ್ದೀರಾ?',
    ready_desc: 'ಬಹು ಬೆಳೆಗಳ ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸಿ, ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ ವೀಕ್ಷಿಸಿ ಮತ್ತು ಖರೀದಿ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    btn_launch_booking: 'ಸ್ಲಾಟ್ ಬುಕಿಂಗ್ ಆರಂಭಿಸಿ',

    detect_location: 'ನನ್ನ ಸ್ಥಳ ಪತ್ತೆಹಚ್ಚಿ (GPS)',
    location_detected: 'ಸ್ಥಳ ಪತ್ತೆಯಾಗಿದೆ',
    select_location: 'ನಿಮ್ಮ ಜಿಲ್ಲೆ / ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    enter_village: 'ಗ್ರಾಮ / ತಾಲೂಕು ಹೆಸರು',
    enter_address: 'ಜಮೀನು / ವಿಳಾಸ',
    district_label: 'ಜಿಲ್ಲೆ',
    state_label: 'ರಾಜ್ಯ',
    gps_accuracy: 'ಜಿಪಿಎಸ್ ಅಂತರ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ',
    near_you: 'ನಿಮಗೆ ಹತ್ತಿರವಿರುವ ಖರೀದಿ ಕೇಂದ್ರಗಳು',

    reg_portal_title: 'ರೈತ ನೋಂದಣಿ ಪೋರ್ಟಲ್',
    reg_create_account: 'ಹೊಸ ರೈತ ಖಾತೆಯನ್ನು ರಚಿಸಿ',
    reg_step1_label: 'ವೈಯಕ್ತಿಕ ಮತ್ತು ಸ್ಥಳ ವಿವರಗಳು',
    reg_step2_label: 'ಬೆಳೆ ವಿವರಗಳು',
    reg_step3_label: 'ಖರೀದಿ ಕೇಂದ್ರ',
    reg_step1_title: 'ಹಂತ 1: ರೈತ ಗುರುತು ಮತ್ತು ಸ್ಥಳ',
    reg_step2_title: 'ಹಂತ 2: ಮುಖ್ಯ ಬೆಳೆ ಮತ್ತು ಇಳುವರಿ ವಿವರಗಳು',
    reg_step3_title: 'ಹಂತ 3: ಆದ್ಯತೆಯ ಖರೀದಿ ಕೇಂದ್ರ',
    full_name_label: 'ಪೂರ್ಣ ಹೆಸರು *',
    name_placeholder: 'ಉದಾ: ರವಿ ಕುಮಾರ್',
    mobile_placeholder: 'ಉದಾ: 9876543210',
    village_placeholder: 'ಉದಾ: ಪೆದಕಾಕಾನಿ',
    address_placeholder: 'ಮನೆ ಸಂಖ್ಯೆ, ರಸ್ತೆ, ಪಿನ್‌ಕೋಡ್',
    crop_type_label: 'ಬೆಳೆ ಪ್ರಕಾರ (27+ ಆಯ್ಕೆಗಳು) *',
    variety_label: 'ತಳಿ / ಗ್ರೇಡ್ *',
    variety_placeholder: 'ಉದಾ: ಸೋನಾ ಮಸೂರಿ ಗ್ರೇಡ್ ಎ',
    expected_qty_label: 'ನಿರೀಕ್ಷಿತ ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್‌ಗಳಲ್ಲಿ) *',
    qty_helper: '1 ಕ್ವಿಂಟಾಲ್ = 100 ಕೆಜಿ. ಸರ್ಕಾರದ ಎಂಎಸ್‌ಪಿ ಅನ್ವಯಿಸುತ್ತದೆ.',
    centres_matching: 'ಲಭ್ಯವಿರುವ ಕೇಂದ್ರಗಳು',
    capacity_per_day: 'ದೈನಂದಿನ ಸಾಮರ್ಥ್ಯ',
    btn_prev_step: 'ಹಿಂದಿನ ಹಂತ',
    btn_next_step: 'ಮುಂದಿನ ಹಂತ',
    btn_complete_reg: 'ನೋಂದಣಿ ಪೂರ್ಣಗೊಳಿಸಿ ಮತ್ತು ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸಿ',
    already_registered: 'ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆಯೇ? ಸೈನ್ ಇನ್ ಮಾಡಿ',

    signin_title: 'ಸ್ಮಾರ್ಟ್‌ಪ್ರೊಕ್ಯೂರ್ ಸೈನ್ ಇನ್',
    signin_desc: 'ರೈತರು ಮತ್ತು ಅಧಿಕಾರಿಗಳಿಗಾಗಿ ಸುರಕ್ಷಿತ ಡಿಜಿಟಲ್ ಲಾಗಿನ್ ಪೋರ್ಟಲ್.',
    tab_farmer: 'ರೈತ',
    tab_officer: 'ಅಧಿಕಾರಿ',
    tab_admin: 'ಅಡ್ಮಿನ್',
    farmer_otp_title: 'ರೈತ ಮೊಬೈಲ್ OTP ಮತ್ತು ಸ್ಥಳ ಲಾಗಿನ್',
    farmer_otp_desc: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ, ಜಿಲ್ಲೆ ಆಯ್ಕೆಮಾಡಿ OTP ಪಡೆಯಿರಿ.',
    mobile_label: 'ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    change_mobile: 'ಮೊಬೈಲ್ ಬದಲಾಯಿಸಿ',
    enter_otp: '4 ಅಂಕಿಗಳ OTP ಕೋಡ್ ನಮೂದಿಸಿ',
    otp_hint: 'ಸುಳಿವು: ನಿಮ್ಮ ಮೊಬೈಲ್‌ಗೆ ಕಳುಹಿಸಲಾದ 4 ಅಂಕಿಗಳ ಕೋಡ್ ನಮೂದಿಸಿ',
    resend_otp: 'OTP ಮರುಕಳುಹಿಸಿ',
    resend_in: 'ಮರುಕಳುಹಿಸುವ ಸಮಯ',
    btn_get_otp: 'OTP ಕೋಡ್ ಪಡೆಯಿರಿ',
    btn_verify_login: 'ದೃಢೀಕರಿಸಿ ಲಾಗಿನ್ ಮಾಡಿ',
    new_farmer_register: 'ಹೊಸ ರೈತರೇ? ನೋಂದಾಯಿಸಿ',
    officer_title: 'ಕೇಂದ್ರ ಅಧಿಕಾರಿ ಲಾಗಿನ್',
    officer_desc: 'ಖರೀದಿ ಕೇಂದ್ರದ ಅಧಿಕಾರಿಗಳ ಲಾಗಿನ್ ಪೋರ್ಟಲ್.',
    station_code: 'ಕೇಂದ್ರದ ಕೋಡ್',
    department_password: 'ಪಾಸ್‌ವರ್ಡ್',
    btn_officer_login_action: 'ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್‌ಗೆ ಲಾಗಿನ್',
    admin_title: 'ಅಡ್ಮಿನ್ ಲಾಗಿನ್',
    admin_desc: 'ಸರ್ಕಾರಿ ಆಡಳಿತ ಮತ್ತು ವಿಶ್ಲೇಷಣಾ ಪೋರ್ಟಲ್.',
    admin_id: 'ಸರ್ಕಾರಿ ಇಮೇಲ್ / ಐಡಿ',
    security_pin: 'ಭದ್ರತಾ ಪಿನ್',
    btn_admin_login_action: 'ಅಡ್ಮಿನ್ ಸೂಟ್ ಪ್ರವೇಶಿಸಿ',
    ssl_encrypted: '256-ಬಿಟ್ SSL ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ',
    aadhaar_integrated: 'ಆಧಾರ್ ಸಂಯೋಜಿತ',
    return_home: '← ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',

    slot_booking_title: 'ಬೆಳೆ ಖರೀದಿ ಸಮಯವನ್ನು ಕಾಯ್ದಿರಿಸಿ',
    select_crops: 'ಬೆಳೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    multi_crop_badge: 'ಬಹು ಬೆಳೆ ಆಯ್ಕೆ',
    add_crop: 'ಮತ್ತೊಂದು ಬೆಳೆ ಸೇರಿಸಿ',
    remove_crop: 'ತೆಗೆದುಹಾಕಿ',
    total_quantity: 'ಒಟ್ಟು ಪ್ರಮಾಣ',
    total_est_payout: 'ಒಟ್ಟು ಅಂದಾಜು ಎಂಎಸ್‌ಪಿ ಮೌಲ್ಯ',
    step_crop: '1. ಬೆಳೆಗಳು',
    step_quantity: '2. ಪ್ರಮಾಣ',
    step_centre: '3. ಕೇಂದ್ರ',
    step_date: '4. ದಿನಾಂಕ',
    step_slot: '5. ಸಮಯ',
    step_summary: '6. ಸಾರಾಂಶ',
    search_crop_placeholder: 'ಬೆಳೆ ಹುಡುಕಿ (ಭತ್ತ, ಹತ್ತಿ, ರಾಗಿ, ಶೇಂಗಾ)...',
    search_centre_placeholder: 'ಕೇಂದ್ರ ಅಥವಾ ಜಿಲ್ಲೆ ಹುಡುಕಿ...',
    all_categories: 'ಎಲ್ಲಾ ವಿಭಾಗಗಳು',
    cereals: 'ಧಾನ್ಯಗಳು',
    pulses: 'ಬೇಳೆಕಾಳುಗಳು',
    oilseeds: 'ಎಣ್ಣೆಕಾಳುಗಳು',
    commercial: 'ವಾಣಿಜ್ಯ ಬೆಳೆಗಳು',
    spices: 'ಮಸಾಲೆ ಬೆಳೆಗಳು',
    est_wait: 'ಕಾಯುವ ಸಮಯ',
    live_queue: 'ಲೈವ್ ಸಾಲು',
    btn_confirm_token: 'ದೃಢೀಕರಿಸಿ ಟೋಕನ್ ಪಡೆಯಿರಿ',

    farmer_dashboard_title: 'ರೈತ ಖರೀದಿ ಕೇಂದ್ರ',
    welcome_farmer: 'ಸ್ವಾಗತ',
    live_token_card: 'ಲೈವ್ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಟೋಕನ್',
    token_now_serving: 'ಈಗ ಸೇವೆ ಪಡೆಯುತ್ತಿರುವ ಟೋಕನ್',
    your_token: 'ನಿಮ್ಮ ಟೋಕನ್ ಸಂಖ್ಯೆ',
    farmers_ahead: 'ಮುಂದಿರುವ ರೈತರು',
    est_wait_time: 'ಅಂದಾಜು ಕಾಯುವ ಸಮಯ',
    quick_actions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    btn_view_token: 'ಡಿಜಿಟಲ್ ಟೋಕನ್ ವೀಕ್ಷಿಸಿ',
    btn_track_queue: 'ಲೈವ್ ಸಾಲು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    btn_procurement_history: 'ಖರೀದಿ ಇತಿಹಾಸ',
    btn_payment_status: 'ಪಾವತಿ ಸ್ಥಿತಿ (DBT)',
    btn_book_new_slot: 'ಹೊಸ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ',

    digital_pass_title: 'ಅಧಿಕೃತ ಡಿಜಿಟಲ್ ಪಾಸ್',
    your_digital_token: 'ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಟೋಕನ್',
    verified_qr_pass: 'ಪರಿಶೀಲಿಸಿದ QR ಪಾಸ್ • ಸ್ಮಾರ್ಟ್‌ಪ್ರೊಕ್ಯೂರ್',
    serving_token: 'ಪ್ರಸ್ತುತ ಟೋಕನ್',
    farmer_label: 'ರೈತ',
    scheduled_slot: 'ನಿಗದಿತ ಸಮಯ',
    procurement_hub: 'ಖರೀದಿ ಕೇಂದ್ರ',
    live_queue_status: 'ಲೈವ್ ಕ್ಯೂ ಸ್ಥಿತಿ',
    live_queue_ahead: 'ರೈತರು ಮುಂದಿದ್ದಾರೆ',
    btn_download_pass: 'ಡಿಜಿಟಲ್ ಪಾಸ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (PDF)',
    btn_track_live_queue: 'ಲೈವ್ ಕ್ಯೂ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',

    queue_tracker_title: 'ನೈಜ ಸಮಯದ ಕ್ಯೂ ಟ್ರ್ಯಾಕರ್',
    now_serving: 'ಈಗ ಸೇವೆ ನೀಡಲಾಗುತ್ತಿದೆ',
    in_queue_line: 'ಸಾಲಿನಲ್ಲಿ',
    queue_progress: 'ಸರತಿ ಪ್ರಗತಿ',
    turn_now: 'ಈಗ ನಿಮ್ಮ ಸರದಿ!',
    farmers_ahead_count: 'ರೈತರು ಮುಂದಿದ್ದಾರೆ',
    live_queue_flow: 'ಲೈವ್ ಟೋಕನ್ ಹರಿವು',
    dynamic_sync: 'ಲೈವ್ ಸಿಂಕ್',
    serving: 'ಸೇವೆಯಲ್ಲಿ',
    you: 'ನೀವು',
    done: 'ಮುಗಿದಿದೆ',
    wait: 'ಕಾಯಿರಿ',
    counter1: 'ಕೌಂಟರ್ 1',

    stage_arrival: 'ಕೇಂದ್ರಕ್ಕೆ ಆಗಮನ',
    stage_moisture: 'ತೇವಾಂಶ ಪರೀಕ್ಷೆ',
    stage_grading: 'ಗುಣಮಟ್ಟ ಶ್ರೇಣೀಕರಣ',
    stage_weighing: 'ವಿದ್ಯುನ್ಮಾನ ತೂಕ',
    stage_voucher: 'ರಶೀದಿ ರಚನೆ',
    stage_dbt: 'ಖಾತೆಗೆ ನೇರ ನಗದು ಜಮೆ',

    payment_title: 'DBT ಪಾವತಿ ಮಾಹಿತಿ ಕೇಂದ್ರ',
    total_paid: 'ಖಾತೆಗೆ ಜಮೆಯಾದ ಒಟ್ಟು ಹಣ',
    pending_amount: 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿರುವ ಹಣ',
    completed_txns: 'ಪೂರ್ಣಗೊಂಡ ವಹಿವಾಟುಗಳು',
    voucher_id: 'ರಶೀದಿ ಸಂಖ್ಯೆ',
    bank_status: 'ಬ್ಯಾಂಕ್ ಸ್ಥಿತಿ',

    footer_text: 'ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳು, ಆಹಾರ ಮತ್ತು ಸಾರ್ವಜನಿಕ ವಿತರಣಾ ಸಚಿವಾಲಯ, ಭಾರತ ಸರ್ಕಾರಕ್ಕಾಗಿ ಅಭಿವೃದ್ಧಿಪಡಿಸಲಾಗಿದೆ.',
    footer_rights: 'ರಾಷ್ಟ್ರೀಯ ಕೃಷಿ ಖರೀದಿ ಪೋರ್ಟಲ್. ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.'
  },

  pa: {
    portal_title: 'ਸਮਾਰਟਪ੍ਰੋਕਿਓਰ',
    govt_title: 'ਖਪਤਕਾਰ ਮਾਮਲੇ, ਖੁਰਾਕ ਅਤੇ ਜਨਤਕ ਵੰਡ ਮੰਤਰਾਲਾ',
    govt_badge: 'ਸਰਕਾਰੀ ਪੋਰਟਲ',
    toll_free: 'ਟੋਲ-ਫ੍ਰੀ ਕਿਸਾਨ ਹੈਲਪਲਾਈਨ',
    nav_dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    nav_book_slot: 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    nav_weather: 'ਮੌਸਮ ਪੂਰਵ ਅਨੁਮਾਨ',
    nav_guidelines: 'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
    nav_my_queue: 'ਮੇਰੀ ਕਤਾਰ',
    nav_procurement: 'ਖਰੀਦ ਸਥਿਤੀ',
    nav_payments: 'ਭੁਗਤਾਨ (DBT)',
    nav_notifications: 'ਸੂਚਨਾਵਾਂ',
    nav_profile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    nav_login: 'ਲਾਗਇਨ',
    nav_register: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    nav_logout: 'ਲਾਗ ਆਊਟ',

    tagline_main: '"ਸਮਾਰਟ ਕਤਾਰਾਂ। ਤੇਜ਼ ਖਰੀਦ। ਬਿਹਤਰ ਕਿਸਾਨੀ।"',
    tagline_desc: 'ਇੱਕ ਆਧੁਨਿਕ ਡਿਜੀਟਲ ਖਰੀਦ ਪ੍ਰਬੰਧਨ ਪਲੇਟਫਾਰਮ ਜੋ ਕਿਸਾਨਾਂ ਦੇ ਉਡੀਕ ਸਮੇਂ ਨੂੰ ਘਟਾਉਂਦਾ ਹੈ, ਮੌਸਮ ਜਾਣਕਾਰੀ ਅਤੇ ਸਿੱਧੇ ਬੈਂਕ ਭੁਗਤਾਨ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।',
    hero_badge: '27+ ਫਸਲਾਂ • 16 ਕੇਂਦਰ • 6 ਭਾਸ਼ਾਵਾਂ',
    btn_farmer_login: 'ਕਿਸਾਨ ਲਾਗਇਨ',
    btn_officer_login: 'ਅਧਿਕਾਰੀ ਲਾਗਇਨ',
    btn_admin_login: 'ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ',

    stat_crops: '27+ ਫਸਲਾਂ',
    stat_crops_sub: 'ਅਨਾਜ, ਦਾਲਾਂ, ਤੇਲ ਬੀਜ, ਨਰਮਾ',
    stat_centres: '16 ਕੇਂਦਰ',
    stat_centres_sub: 'ਅੰਤਰ-ਰਾਜੀ ਕੇਂਦਰ',
    stat_wait_time: '32 ਮਿੰਟ',
    stat_wait_time_sub: 'ਔਸਤ ਉਡੀਕ ਸਮਾਂ (65% ਘੱਟ)',
    stat_dbt: '100%',
    stat_dbt_sub: 'ਸਿੱਧਾ ਲਾਭ ਤਬਾਦਲਾ (DBT)',

    key_features_heading: 'ਪਲੇਟਫਾਰਮ ਦੀਆਂ ਮੁੱਖ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    key_features_subheading: 'ਭਾਰਤ ਭਰ ਦੇ ਖਰੀਦ ਕੇਂਦਰਾਂ ਵਿੱਚ ਡਿਜੀਟਲ ਸਹੂਲਤ, ਮੌਸਮ ਜਾਣਕਾਰੀ, ਬਹੁ-ਫਸਲੀ ਸਹਾਇਤਾ ਅਤੇ ਬਹੁ-ਭਾਸ਼ਾਈ ਪਹੁੰਚ ਪ੍ਰਦਾਨ ਕਰਨ ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਹੈ।',
    feat_multicrop_title: 'ਮਲਟੀ-ਫਸਲੀ ਸਲਾਟ ਅਲਾਟਮੈਂਟ',
    feat_multicrop_desc: 'ਇੱਕੋ ਟਿਕਟ ਵਿੱਚ 27+ ਮੁੱਖ ਫਸਲਾਂ (ਅਨਾਜ, ਦਾਲਾਂ, ਤੇਲ ਬੀਜ, ਨਰਮਾ) ਲਈ ਇਕੱਠੇ ਸਲਾਟ ਬੁੱਕ ਕਰੋ।',
    feat_location_title: 'ਆਟੋ-ਲੋਕੇਸ਼ਨ ਅਤੇ ਨੇੜਲੇ ਕੇਂਦਰ',
    feat_location_desc: 'ਜੀਪੀਐਸ ਦੁਆਰਾ ਨੇੜਲੇ ਖਰੀਦ ਕੇਂਦਰਾਂ ਦੀ ਦੂਰੀ ਅਤੇ ਕਤਾਰ ਦੀ ਸਥਿਤੀ ਆਪਣੇ ਆਪ ਜਾਣੋ।',
    feat_language_title: 'ਬਹੁ-ਭਾਸ਼ਾਈ ਸਹੂਲਤ',
    feat_language_desc: 'ਅੰਗਰੇਜ਼ੀ, ਪੰਜਾਬੀ, ਹਿੰਦੀ, ਤੇਲਗੂ, ਤਾਮਿਲ ਅਤੇ ਕੰਨੜ ਵਿੱਚ ਪੂਰੀ ਖੇਤਰੀ ਭਾਸ਼ਾ ਸਹਾਇਤਾ।',
    feat_queue_title: 'ਲਾਈਵ ਕਤਾਰ ਅਤੇ ਉਡੀਕ ਅਨੁਮਾਨ',
    feat_queue_desc: 'ਮੰਡੀ ਪਹੁੰਚਣ ਤੋਂ ਪਹਿਲਾਂ ਹੀ ਆਪਣਾ ਟੋਕਨ ਨੰਬਰ ਅਤੇ ਅਨੁਮਾਨਿਤ ਉਡੀਕ ਸਮਾਂ ਜਾਣੋ।',
    feat_pipeline_title: 'ਖਰੀਦ ਪ੍ਰਕਿਰਿਆ ਲਾਈਵ ਟਰੈਕਿੰਗ',
    feat_pipeline_desc: 'ਆਮਦ ਤੋਂ ਲੈ ਕੇ ਨਮੀ ਦੀ ਜਾਂਚ ਅਤੇ ਗੁਣਵੱਤਾ ਗ੍ਰੇਡਿੰਗ ਤੱਕ 8-ਪੜਾਵੀ ਪ੍ਰਕਿਰਿਆ ਦੇਖੋ।',
    feat_dbt_title: 'ਸਿੱਧਾ DBT ਬੈਂਕ ਭੁਗਤਾਨ ਪਾਰਦਰਸ਼ਤਾ',
    feat_dbt_desc: 'ਜਾਣੋ ਕਿ ਤੁਹਾਡੀ ਫਸਲ ਦੀ ਰਕਮ ਸਿੱਧੇ ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਕਦੋਂ ਜਮ੍ਹਾ ਹੋਈ ਹੈ।',

    how_it_works: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    how_desc: 'ਆਸਾਨ 6-ਪੜਾਵੀ ਖਰੀਦ ਪ੍ਰਕਿਰਿਆ',
    step1_title: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ / ਲਾਗਇਨ',
    step1_desc: 'ਮੋਬਾਈਲ OTP ਨਾਲ ਲਾਗਇਨ ਕਰੋ',
    step2_title: 'ਫਸਲਾਂ ਚੁਣੋ',
    step2_desc: 'ਇੱਕ ਜਾਂ ਵੱਧ ਫਸਲਾਂ ਦੀ ਚੋਣ ਕਰੋ',
    step3_title: 'ਨੇੜਲਾ ਕੇਂਦਰ',
    step3_desc: 'ਜੀਪੀਐਸ ਦੁਆਰਾ ਨੇੜਲਾ ਕੇਂਦਰ ਚੁਣੋ',
    step4_title: 'ਟੋਕਨ ਤੇ QR ਪ੍ਰਾਪਤ ਕਰੋ',
    step4_desc: 'ਡਿਜੀਟਲ ਪਾਸ ਪ੍ਰਾਪਤ ਕਰੋ',
    step5_title: 'ਲਾਈਵ ਕਤਾਰ ਟਰੈਕਿੰਗ',
    step5_desc: 'ਟੋਕਨ ਪੁਕਾਰਨ ਤੇ ਮੰਡੀ ਪਹੁੰਚੋ',
    step6_title: 'ਸਿੱਧਾ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਜਮ੍ਹਾ',
    step6_desc: 'MSP ਰਸੀਦ ਅਤੇ ਬੈਂਕ ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰੋ',

    ready_cta: 'ਜ਼ੀਰੋ-ਵੇਟ ਖਰੀਦ ਲਈ ਤਿਆਰ ਹੋ?',
    ready_desc: 'ਮਲਟੀ-ਫਸਲੀ ਸਲਾਟ ਬੁੱਕ ਕਰੋ, ਮੌਸਮ ਜਾਣਕਾਰੀ ਵੇਖੋ ਅਤੇ ਸਿੱਧੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰੋ।',
    btn_launch_booking: 'ਸਲਾਟ ਬੁਕਿੰਗ ਸ਼ੁਰੂ ਕਰੋ',

    detect_location: 'ਮੇਰੀ ਲੋਕੇਸ਼ਨ ਲੱਭੋ (GPS)',
    location_detected: 'ਲੋਕੇਸ਼ਨ ਲੱਭ ਗਈ',
    select_location: 'ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ / ਸਥਾਨ ਚੁਣੋ',
    enter_village: 'ਪਿੰਡ / ਤਹਿਸੀਲ ਦਾ ਨਾਮ',
    enter_address: 'ਖੇਤ / ਰਿਹਾਇਸ਼ੀ ਪਤਾ',
    district_label: 'ਜ਼ਿਲ੍ਹਾ',
    state_label: 'ਰਾਜ',
    gps_accuracy: 'ਜੀਪੀਐਸ ਦੂਰੀ ਦੀ ਗਣਨਾ ਕੀਤੀ ਗਈ',
    near_you: 'ਨੇੜਲੇ ਖਰੀਦ ਕੇਂਦਰ',

    reg_portal_title: 'ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੋਰਟਲ',
    reg_create_account: 'ਨਵਾਂ ਕਿਸਾਨ ਖਾਤਾ ਬਣਾਓ',
    reg_step1_label: 'ਨਿੱਜੀ ਅਤੇ ਸਥਾਨ ਵੇਰਵੇ',
    reg_step2_label: 'ਫਸਲ ਦੇ ਵੇਰਵੇ',
    reg_step3_label: 'ਖਰੀਦ ਕੇਂਦਰ',
    reg_step1_title: 'ਪੜਾਅ 1: ਕਿਸਾਨ ਪਛਾਣ ਅਤੇ ਸਥਾਨ',
    reg_step2_title: 'ਪੜਾਅ 2: ਮੁੱਖ ਫਸਲ ਅਤੇ ਝਾੜ ਦੇ ਵੇਰਵੇ',
    reg_step3_title: 'ਪੜਾਅ 3: ਤਰਜੀਹੀ ਖਰੀਦ ਕੇਂਦਰ',
    full_name_label: 'ਪੂਰਾ ਨਾਮ *',
    name_placeholder: 'ਜਿਵੇਂ ਰਵੀ ਕੁਮਾਰ',
    mobile_placeholder: 'ਜਿਵੇਂ 9876543210',
    village_placeholder: 'ਜਿਵੇਂ ਪੇਦਾਕਾਕਾਨੀ',
    address_placeholder: 'ਮਕਾਨ ਨੰਬਰ, ਗਲੀ, ਪਿੰਨ ਕੋਡ',
    crop_type_label: 'ਫਸਲ ਦੀ ਕਿਸਮ (27+ ਵਿਕਲਪ) *',
    variety_label: 'ਕਿਸਮ / ਗ੍ਰੇਡ *',
    variety_placeholder: 'ਜਿਵੇਂ ਸੋਨਾ ਮਸੂਰੀ ਗ੍ਰੇਡ ਏ',
    expected_qty_label: 'ਅਨੁਮਾਨਿਤ ਮਾਤਰਾ (ਕੁਇੰਟਲ ਵਿੱਚ) *',
    qty_helper: '1 ਕੁਇੰਟਲ = 100 ਕਿਲੋਗ੍ਰਾਮ। ਸਰਕਾਰੀ ਘੱਟੋ-ਘੱਟ ਸਮਰਥਨ ਮੁੱਲ (MSP) ਲਾਗੂ।',
    centres_matching: 'ਉਪਲਬਧ ਖਰੀਦ ਕੇਂਦਰ',
    capacity_per_day: 'ਰੋਜ਼ਾਨਾ ਸਮਰੱਥਾ',
    btn_prev_step: 'ਪਿਛਲਾ ਪੜਾਅ',
    btn_next_step: 'ਅਗਲਾ ਪੜਾਅ',
    btn_complete_reg: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੂਰੀ ਕਰੋ ਅਤੇ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    already_registered: 'ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੋ? ਇੱਥੇ ਸਾਈਨ ਇਨ ਕਰੋ',

    signin_title: 'ਸਮਾਰਟਪ੍ਰੋਕਿਓਰ ਏਕੀਕ੍ਰਿਤ ਸਾਈਨ ਇਨ',
    signin_desc: 'ਕਿਸਾਨਾਂ ਅਤੇ ਅਧਿਕਾਰੀਆਂ ਲਈ ਸੁਰੱਖਿਅਤ ਡਿਜੀਟਲ ਲਾਗਇਨ।',
    tab_farmer: 'ਕਿਸਾਨ',
    tab_officer: 'ਅਧਿਕਾਰੀ',
    tab_admin: 'ਐਡਮਿਨ',
    farmer_otp_title: 'ਕਿਸਾਨ ਮੋਬਾਈਲ OTP ਅਤੇ ਸਥਾਨ ਲਾਗਇਨ',
    farmer_otp_desc: 'ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ, ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ ਅਤੇ OTP ਪ੍ਰਾਪਤ ਕਰੋ।',
    mobile_label: 'ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ',
    change_mobile: 'ਮੋਬਾਈਲ ਬਦਲੋ',
    enter_otp: '4 ਅੰਕਾਂ ਦਾ OTP ਦਰਜ ਕਰੋ',
    otp_hint: 'ਸੰਕੇਤ: ਆਪਣੇ ਮੋਬਾਈਲ ਤੇ ਪ੍ਰਾਪਤ 4 ਅੰਕਾਂ ਦਾ ਕੋਡ ਦਰਜ ਕਰੋ',
    resend_otp: 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
    resend_in: 'ਦੁਬਾਰਾ ਭੇਜਣ ਦਾ ਸਮਾਂ',
    btn_get_otp: 'OTP ਕੋਡ ਪ੍ਰਾਪਤ ਕਰੋ',
    btn_verify_login: 'ਤਸਦੀਕ ਕਰੋ ਅਤੇ ਡੈਸ਼ਬੋਰਡ ਖੋਲ੍ਹੋ',
    new_farmer_register: 'ਨਵੇਂ ਕਿਸਾਨ? ਇੱਥੇ ਰਜਿਸਟਰ ਕਰੋ',
    officer_title: 'ਕੇਂਦਰ ਅਧਿਕਾਰੀ ਲਾਗਇਨ',
    officer_desc: 'ਖਰੀਦ ਕੇਂਦਰ ਅਧਿਕਾਰੀਆਂ ਲਈ ਲਾਗਇਨ ਪੋਰਟਲ।',
    station_code: 'ਕੇਂਦਰ ਕੋਡ',
    department_password: 'ਪਾਸਵਰਡ',
    btn_officer_login_action: 'ਅਧਿਕਾਰੀ ਪੋਰਟਲ ਵਿੱਚ ਦਾਖਲ ਹੋਵੋ',
    admin_title: 'ਐਡਮਿਨ ਲਾਗਇਨ',
    admin_desc: 'ਸਰਕਾਰੀ ਪ੍ਰਸ਼ਾਸਨ ਪੋਰਟਲ।',
    admin_id: 'ਸਰਕਾਰੀ ਈਮੇਲ / ਆਈਡੀ',
    security_pin: 'ਸੁਰੱਖਿਆ ਪਿੰਨ',
    btn_admin_login_action: 'ਐਡਮਿਨ ਸੂਟ ਵਿੱਚ ਦਾਖਲ ਹੋਵੋ',
    ssl_encrypted: '256-ਬਿੱਟ SSL ਸੁਰੱਖਿਅਤ',
    aadhaar_integrated: 'ਆਧਾਰ ਏਕੀਕ੍ਰਿਤ',
    return_home: '← ਮੁੱਖ ਪੰਨੇ ਤੇ ਵਾਪਸ ਜਾਓ',

    slot_booking_title: 'ਖਰੀਦ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    select_crops: 'ਫਸਲਾਂ ਚੁਣੋ',
    multi_crop_badge: 'ਬਹੁ-ਫਸਲੀ ਚੋਣ',
    add_crop: 'ਇੱਕ ਹੋਰ ਫਸਲ ਜੋੜੋ',
    remove_crop: 'ਹਟਾਓ',
    total_quantity: 'ਕੁੱਲ ਮਾਤਰਾ',
    total_est_payout: 'ਕੁੱਲ ਅਨੁਮਾਨਿਤ MSP ਭੁਗਤਾਨ',
    step_crop: '1. ਫਸਲਾਂ',
    step_quantity: '2. ਮਾਤਰਾ',
    step_centre: '3. ਕੇਂਦਰ',
    step_date: '4. ਮਿਤੀ',
    step_slot: '5. ਸਮਾਂ',
    step_summary: '6. ਵੇਰਵਾ',
    search_crop_placeholder: 'ਫਸਲ ਖੋਜੋ (ਕਣਕ, ਝੋਨਾ, ਨਰਮਾ, ਸਰ੍ਹੋਂ)...',
    search_centre_placeholder: 'ਕੇਂਦਰ ਜਾਂ ਜ਼ਿਲ੍ਹਾ ਖੋਜੋ...',
    all_categories: 'ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ',
    cereals: 'ਅਨਾਜ',
    pulses: 'ਦਾਲਾਂ',
    oilseeds: 'ਤੇਲ ਬੀਜ',
    commercial: 'ਵਪਾਰਕ ਫਸਲਾਂ',
    spices: 'ਮਸਾਲੇ',
    est_wait: 'ਉਡੀਕ ਸਮਾਂ',
    live_queue: 'ਲਾਈਵ ਕਤਾਰ',
    btn_confirm_token: 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਟੋਕਨ ਪ੍ਰਾਪਤ ਕਰੋ',

    farmer_dashboard_title: 'ਕਿਸਾਨ ਖਰੀਦ ਪੋਰਟਲ',
    welcome_farmer: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    live_token_card: 'ਸਰਗਰਮ ਟੋਕਨ',
    token_now_serving: 'ਹੁਣ ਸੇਵਾ ਦਿੱਤੀ ਜਾ ਰਹੀ ਟੋਕਨ',
    your_token: 'ਤੁਹਾਡਾ ਟੋਕਨ ਨੰਬਰ',
    farmers_ahead: 'ਅੱਗੇ ਕਿਸਾਨ',
    est_wait_time: 'ਅਨੁਮਾਨਿਤ ਉਡੀਕ ਸਮਾਂ',
    quick_actions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
    btn_view_token: 'ਡਿਜੀਟਲ ਟੋਕਨ ਦੇਖੋ',
    btn_track_queue: 'ਲਾਈਵ ਕਤਾਰ ਟਰੈਕ ਕਰੋ',
    btn_procurement_history: 'ਖਰੀਦ ਇਤਿਹਾਸ',
    btn_payment_status: 'ਭੁਗਤਾਨ ਸਥਿਤੀ (DBT)',
    btn_book_new_slot: 'ਨਵਾਂ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',

    digital_pass_title: 'ਅਧਿਕਾਰਤ ਡਿਜੀਟਲ ਪਾਸ',
    your_digital_token: 'ਤੁਹਾਡਾ ਡਿਜੀਟਲ ਟੋਕਨ',
    verified_qr_pass: 'ਪ੍ਰਮਾਣਿਤ QR ਪਾਸ • ਸਮਾਰਟਪ੍ਰੋਕਿਓਰ',
    serving_token: 'ਮੌਜੂਦਾ ਟੋਕਨ',
    farmer_label: 'ਕਿਸਾਨ',
    scheduled_slot: 'ਨਿਰਧਾਰਤ ਸਮਾਂ',
    procurement_hub: 'ਖਰੀਦ ਕੇਂਦਰ',
    live_queue_status: 'ਲਾਈਵ ਕਤਾਰ ਸਥਿਤੀ',
    live_queue_ahead: 'ਕਿਸਾਨ ਅੱਗੇ ਹਨ',
    btn_download_pass: 'ਡਿਜੀਟਲ ਪਾਸ ਡਾਊਨਲੋਡ ਕਰੋ (PDF)',
    btn_track_live_queue: 'ਲਾਈਵ ਕਤਾਰ ਟਰੈਕ ਕਰੋ',

    queue_tracker_title: 'ਰੀਅਲ-ਟਾਈਮ ਕਤਾਰ ਟਰੈਕਰ',
    now_serving: 'ਮੌਜੂਦਾ ਸੇਵਾ',
    in_queue_line: 'ਕਤਾਰ ਵਿੱਚ',
    queue_progress: 'ਕਤਾਰ ਦੀ ਪ੍ਰਗਤੀ',
    turn_now: 'ਹੁਣ ਤੁਹਾਡੀ ਵਾਰੀ ਹੈ!',
    farmers_ahead_count: 'ਕਿਸਾਨ ਅੱਗੇ ਹਨ',
    live_queue_flow: 'ਲਾਈਵ ਟੋਕਨ ਪ੍ਰਵਾਹ',
    dynamic_sync: 'ਲਾਈਵ ਸਿੰਕ',
    serving: 'ਸੇਵਾ ਵਿੱਚ',
    you: 'ਤੁਸੀਂ',
    done: 'ਪੂਰਾ ਹੋਇਆ',
    wait: 'ਉਡੀਕ ਕਰੋ',
    counter1: 'ਕਾਊਂਟਰ 1',

    stage_arrival: 'ਕੇਂਦਰ ਪਹੁੰਚਣਾ',
    stage_moisture: 'ਨਮੀ ਦੀ ਜਾਂਚ',
    stage_grading: 'ਗੁਣਵੱਤਾ ਦਰਜਾਬੰਦੀ',
    stage_weighing: 'ਇਲੈਕਟ੍ਰਾਨਿਕ ਤੋਲ',
    stage_voucher: 'ਰਸੀਦ ਜਾਰੀ',
    stage_dbt: 'ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਜਮ੍ਹਾ',

    payment_title: 'DBT ਭੁਗਤਾਨ ਸੂਚਨਾ ਕੇਂਦਰ',
    total_paid: 'ਖਾਤੇ ਵਿੱਚ ਪ੍ਰਾਪਤ ਕੁੱਲ ਰਕਮ',
    pending_amount: 'ਪ੍ਰਕਿਰਿਆ ਅਧੀਨ ਰਕਮ',
    completed_txns: 'ਸਫਲ ਲੈਣ-ਦੇਣ',
    voucher_id: 'ਵਾਊਚਰ ਨੰਬਰ',
    bank_status: 'ਬੈਂਕ ਜਮ੍ਹਾ ਸਥਿਤੀ',

    footer_text: 'ਖਪਤਕਾਰ ਮਾਮਲੇ, ਖੁਰਾਕ ਅਤੇ ਜਨਤਕ ਵੰਡ ਮੰਤਰਾਲਾ, ਭਾਰਤ ਸਰਕਾਰ ਲਈ ਵਿਕਸਤ।',
    footer_rights: 'ਰਾਸ਼ਟਰੀ ਖੇਤੀਬਾੜੀ ਖਰੀਦ ਪੋਰਟਲ। ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।'
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  currentLanguage: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('smartprocure_lang') as LanguageCode;
    return saved && translations[saved] ? saved : 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('smartprocure_lang', lang);
  };

  const t = (key: string): string => {
    const langDict = translations[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    return translations.en[key] || key;
  };

  const currentLanguage = languages.find(l => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
